// ============================================================
// Omiyage Go - 全国対応モックデータ（都内38件 + 全国60件）
// デザイン哲学: 駅ホーム案内板スタイル - 情報の読み取り速度最優先
// データソース: 全国主要観光地・空港・駅・百貨店
// ============================================================

export type BadgeType = "editorial" | "local" | "corporate";
export type TemperatureType = "常温" | "冷蔵" | "冷凍";
export type GateStatus = "改札内" | "改札外";
export type FacilityId =
  | "tokyo"
  | "haneda_t1"
  | "haneda_t2"
  | "haneda_t3"
  | "shinagawa"
  | "shinjuku"
  | "shibuya"
  | "chitose"
  | "kyoto"
  | "osaka"
  | "fukuoka"
  | "naha"
  | "hiroshima"
  | "nagoya"
  | "kanazawa"
  | "sendai"
  | "nagano"
  | "shizuoka"
  | "nara"
  | "kagoshima"
  | "nagasaki"
  | "kumamoto"
  | "all";

export type RegionId = "北海道" | "東北" | "関東" | "中部" | "近畿" | "中国" | "四国" | "九州・沖縄" | "all";

export interface FacilityInfo {
  id: FacilityId;
  label: string;
  shortLabel: string;
  coords: { lat: number; lng: number };
}

export const FACILITIES: FacilityInfo[] = [
  { id: "all", label: "すべての施設", shortLabel: "すべて", coords: { lat: 35.6812, lng: 139.7671 } },
  { id: "tokyo", label: "東京駅", shortLabel: "東京駅", coords: { lat: 35.6812, lng: 139.7671 } },
  { id: "haneda_t1", label: "羽田空港 第1ターミナル", shortLabel: "羽田T1", coords: { lat: 35.5494, lng: 139.7798 } },
  { id: "haneda_t2", label: "羽田空港 第2ターミナル", shortLabel: "羽田T2", coords: { lat: 35.5494, lng: 139.7798 } },
  { id: "haneda_t3", label: "羽田空港 第3ターミナル（国際線）", shortLabel: "羽田T3", coords: { lat: 35.5494, lng: 139.7798 } },
  { id: "shinagawa", label: "品川駅", shortLabel: "品川駅", coords: { lat: 35.6284, lng: 139.7387 } },
  { id: "shinjuku", label: "新宿駅", shortLabel: "新宿駅", coords: { lat: 35.6896, lng: 139.7006 } },
  { id: "shibuya", label: "渋谷駅", shortLabel: "渋谷駅", coords: { lat: 35.6591, lng: 139.7030 } },
  { id: "chitose", label: "新千歳空港", shortLabel: "新千歳", coords: { lat: 42.7752, lng: 141.6922 } },
  { id: "kyoto", label: "京都駅", shortLabel: "京都駅", coords: { lat: 34.9858, lng: 135.7588 } },
  { id: "osaka", label: "大阪駅・新大阪駅", shortLabel: "大阪駅", coords: { lat: 34.7024, lng: 135.4959 } },
  { id: "fukuoka", label: "博多駅・福岡空港", shortLabel: "博多駅", coords: { lat: 33.5903, lng: 130.4207 } },
  { id: "naha", label: "那覇空港・国際通り", shortLabel: "那覇", coords: { lat: 26.2124, lng: 127.6492 } },
  { id: "hiroshima", label: "広島駅・広島空港", shortLabel: "広島駅", coords: { lat: 34.3963, lng: 132.4596 } },
  { id: "nagoya", label: "名古屋駅・中部国際空港", shortLabel: "名古屋", coords: { lat: 35.1709, lng: 136.8815 } },
  { id: "kanazawa", label: "金沢駅", shortLabel: "金沢駅", coords: { lat: 36.5781, lng: 136.6480 } },
  { id: "sendai", label: "仙台駅・仙台空港", shortLabel: "仙台駅", coords: { lat: 38.2682, lng: 140.8694 } },
  { id: "nagano", label: "長野駅・松本駅", shortLabel: "長野駅", coords: { lat: 36.6485, lng: 138.1950 } },
  { id: "shizuoka", label: "静岡駅・浜松駅", shortLabel: "静岡駅", coords: { lat: 34.9756, lng: 138.3828 } },
  { id: "nara", label: "近鉄奈良駅・JR奈良駅", shortLabel: "奈良駅", coords: { lat: 34.6851, lng: 135.8048 } },
  { id: "kagoshima", label: "鹿児島中央駅", shortLabel: "鹿児島", coords: { lat: 31.5785, lng: 130.5432 } },
  { id: "nagasaki", label: "長崎駅・長崎空港", shortLabel: "長崎駅", coords: { lat: 32.7503, lng: 129.8779 } },
  { id: "kumamoto", label: "熊本駅・熊本空港", shortLabel: "熊本駅", coords: { lat: 32.7898, lng: 130.7417 } },
];

export const REGIONS: { id: RegionId; label: string; prefectures: string[] }[] = [
  { id: "all", label: "全国", prefectures: [] },
  { id: "北海道", label: "北海道", prefectures: ["北海道"] },
  { id: "東北", label: "東北", prefectures: ["青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県"] },
  { id: "関東", label: "関東", prefectures: ["東京都", "神奈川県", "埼玉県", "千葉県", "茨城県", "栃木県", "群馬県"] },
  { id: "中部", label: "中部", prefectures: ["新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県", "静岡県", "愛知県"] },
  { id: "近畿", label: "近畿", prefectures: ["大阪府", "京都府", "兵庫県", "奈良県", "和歌山県", "滋賀県"] },
  { id: "中国", label: "中国", prefectures: ["鳥取県", "島根県", "岡山県", "広島県", "山口県"] },
  { id: "四国", label: "四国", prefectures: ["徳島県", "香川県", "愛媛県", "高知県"] },
  { id: "九州・沖縄", label: "九州・沖縄", prefectures: ["福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"] },
];

export interface Seller {
  id: string;
  facilityId: FacilityId;
  facilityName: string;
  shopName: string;
  gateStatus: GateStatus;
  floor: string;
  landmark: string;
  walkingMinutes: number;
  crowdLevel: "少" | "中" | "多";
  openHours: string;
  mapUrl: string;
  coords: { lat: number; lng: number };
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  priceLabel: string;
  imageUrl: string;
  badges: BadgeType[];
  badgeLabels: string[];
  category: string;
  // 制約
  shelfLifeDays: number;
  individuallyWrapped: boolean;
  recommendedCount: number;
  temperature: TemperatureType;
  allergens: string[];
  // 保証書
  guaranteeReasons: string[];
  guaranteeOneLiner: string;
  // 文脈
  makerQuote: string;
  makerStory: string;
  makerName: string;
  // 贈り文テンプレ
  giftTemplates: {
    greeting: string;
    thanks: string;
    apology: string;
  };
  // 売り場
  sellers: Seller[];
  // 受取・配送
  canReserve: boolean;
  canPrePay: boolean;
  canDeliver: boolean;
  // 在庫状態
  stockStatus: "available" | "soldout_risk" | "unknown";
  // 用途タグ
  purposes: string[];
  // 予算カテゴリ
  budgetCategory: 1000 | 2000 | 3000 | 5000;
  // 産地情報
  prefecture?: string;  // 例: "北海道"
  region?: RegionId;    // 例: "北海道"
}

// ── 画像URLプール（Unsplash） ──────────────────────────────────
const IMG = {
  wagashi: "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=600&q=80",
  cookie: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80",
  cake: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
  chocolate: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
  butter: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80",
  cheese: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&q=80",
  jelly: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80",
  snack: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
  financier: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&q=80",
  mochi: "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=600&q=80",
  tart: "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=600&q=80",
  rusk: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80",
  macaron: "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=600&q=80",
  gift: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80",
  sandwich: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80",
};

// ── ヘルパー関数 ──────────────────────────────────────────────
function tokyoSeller(id: string, shopName: string, gate: GateStatus, floor = "B1F", minutes = 5): Seller {
  return {
    id,
    facilityId: "tokyo",
    facilityName: "東京駅 グランスタ東京",
    shopName,
    gateStatus: gate,
    floor,
    landmark: gate === "改札内" ? "グランスタ東京 改札内エリア" : "東京ギフトパレット（改札外）",
    walkingMinutes: minutes,
    crowdLevel: "多",
    openHours: "8:00〜22:00",
    mapUrl: "https://maps.google.com/?q=グランスタ東京",
    coords: { lat: 35.6812, lng: 139.7671 },
  };
}

function hanetaSeller(id: string, shopName: string, terminal: "haneda_t1" | "haneda_t2" | "haneda_t3", gate: GateStatus, floor = "2F"): Seller {
  const terminalLabel = terminal === "haneda_t1" ? "第1ターミナル" : terminal === "haneda_t2" ? "第2ターミナル" : "第3ターミナル（国際線）";
  return {
    id,
    facilityId: terminal,
    facilityName: `羽田空港 ${terminalLabel}`,
    shopName,
    gateStatus: gate,
    floor,
    landmark: gate === "改札内" ? "保安検査場内ショップ" : `${terminalLabel} 出発ロビー`,
    walkingMinutes: 3,
    crowdLevel: "中",
    openHours: "6:00〜21:00",
    mapUrl: `https://maps.google.com/?q=羽田空港${terminalLabel}`,
    coords: { lat: 35.5494, lng: 139.7798 },
  };
}

function shinagawaSeller(id: string, shopName: string, gate: GateStatus, floor = "1F"): Seller {
  return {
    id,
    facilityId: "shinagawa",
    facilityName: gate === "改札内" ? "品川駅 エキュート品川" : "品川駅 アトレ品川",
    shopName,
    gateStatus: gate,
    floor,
    landmark: gate === "改札内" ? "エキュート品川 改札内" : "アトレ品川 改札外",
    walkingMinutes: gate === "改札内" ? 3 : 5,
    crowdLevel: "中",
    openHours: "7:00〜22:00",
    mapUrl: "https://maps.google.com/?q=品川駅エキュート",
    coords: { lat: 35.6284, lng: 139.7387 },
  };
}

function shinjukuSeller(id: string, shopName: string, gate: GateStatus, building = "伊勢丹新宿店"): Seller {
  return {
    id,
    facilityId: "shinjuku",
    facilityName: `新宿駅 ${building}`,
    shopName,
    gateStatus: gate,
    floor: "B1F",
    landmark: building,
    walkingMinutes: gate === "改札内" ? 2 : 8,
    crowdLevel: "多",
    openHours: "10:00〜20:00",
    mapUrl: "https://maps.google.com/?q=伊勢丹新宿店",
    coords: { lat: 35.6896, lng: 139.7006 },
  };
}

function shibuyaSeller(id: string, shopName: string, gate: GateStatus, building = "渋谷スクランブルスクエア"): Seller {
  return {
    id,
    facilityId: "shibuya",
    facilityName: `渋谷駅 ${building}`,
    shopName,
    gateStatus: gate,
    floor: "2F",
    landmark: building,
    walkingMinutes: gate === "改札内" ? 3 : 7,
    crowdLevel: "中",
    openHours: "10:00〜21:00",
    mapUrl: "https://maps.google.com/?q=渋谷スクランブルスクエア",
    coords: { lat: 35.6591, lng: 139.7030 },
  };
}

// ── 商品データ ────────────────────────────────────────────────
export const PRODUCTS: Product[] = [
  // ─────────────────────────────────────────────────────────────
  // 東京駅 グランスタ東京（改札内）
  // ─────────────────────────────────────────────────────────────
  {
    id: "p001",
    name: "クレームブリュレタルト",
    brand: "喫茶店に恋して。",
    price: 950,
    priceLabel: "¥950（税込）",
    imageUrl: IMG.tart,
    badges: ["editorial"],
    badgeLabels: ["累計500万個突破"],
    category: "スイーツ",
    shelfLifeDays: 20,
    individuallyWrapped: true,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "累計販売数500万個突破の実績",
      "パリとろ食感で話題性抜群",
      "個包装でシェアしやすい",
      "東京駅グランスタ改札内で購入可能",
      "日持ち20日で余裕を持って渡せる",
    ],
    guaranteeOneLiner: "累計500万個突破のパリとろタルト。改札内で即購入できる話題品",
    makerQuote: "「パリッとした食感の中に、とろけるブリュレクリームを閉じ込めました」",
    makerStory: "グランスタ東京に出店する人気スイーツブランド。本の形をしたパッケージが特徴的で、SNSでも話題沸騰中。",
    makerName: "喫茶店に恋して。 パティシエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。東京で話題のタルトをお持ちしました。",
      thanks: "先日はありがとうございました。累計500万個突破のタルトです。お口に合えば幸いです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p001", "喫茶店に恋して。 グランスタ東京店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 1000,
  },
  {
    id: "p002",
    name: "サンドクッキー ヘーゼルナッツと木苺",
    brand: "COCORIS",
    price: 1560,
    priceLabel: "¥1,560（税込）",
    imageUrl: IMG.cookie,
    badges: ["editorial"],
    badgeLabels: ["連日大行列"],
    category: "クッキー",
    shelfLifeDays: 45,
    individuallyWrapped: true,
    recommendedCount: 8,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳", "アーモンド"],
    guaranteeReasons: [
      "東京駅でしか買えない限定品",
      "連日大行列の人気スイーツ専門店",
      "日持ち45日以上で余裕を持って渡せる",
      "パッケージデザインが洗練されている",
      "個包装で配りやすい",
    ],
    guaranteeOneLiner: "東京駅限定・連日大行列のサンドクッキー。スイーツ好きへの手土産に",
    makerQuote: "「東京でしか出会えない特別な味を追求しています」",
    makerStory: "グランスタ東京に出店する人気スイーツ専門店。ヘーゼルナッツと木苺の組み合わせが絶妙で、スイーツ通の間でも評判。",
    makerName: "COCORIS パティシエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。東京駅限定のサンドクッキーをお持ちしました。",
      thanks: "先日はありがとうございました。東京駅でしか買えないクッキーです。ぜひお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。お詫びの気持ちとしてお受け取りください。",
    },
    sellers: [tokyoSeller("s_p002", "COCORIS グランスタ東京店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "soldout_risk",
    purposes: ["挨拶", "御礼", "自分用"],
    budgetCategory: 2000,
  },
  {
    id: "p003",
    name: "メープルクッキー詰合せ缶",
    brand: "ザ・メープルマニア",
    price: 2500,
    priceLabel: "¥2,500（税込）",
    imageUrl: IMG.cookie,
    badges: ["editorial"],
    badgeLabels: ["グランスタ限定缶"],
    category: "クッキー",
    shelfLifeDays: 60,
    individuallyWrapped: true,
    recommendedCount: 15,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "グランスタ限定デザインの特別缶",
      "メープルバタークッキーとショコラクッキーの詰め合わせ",
      "日持ち60日以上で安心",
      "缶が小物入れとして再利用できる",
      "幅広い年代に喜ばれる定番品",
    ],
    guaranteeOneLiner: "グランスタ限定缶に入ったメープルクッキー。缶の再利用も喜ばれる",
    makerQuote: "「メープルの豊かな香りと甘さを、最高のクッキーで表現しました」",
    makerStory: "東京駅グランスタに出店するメープルスイーツ専門店。カナダ産メープルシロップにこだわり、毎日焼き立てのクッキーを提供。",
    makerName: "ザ・メープルマニア 職人",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。東京駅限定のメープルクッキー缶をお持ちしました。",
      thanks: "先日はありがとうございました。グランスタ限定のメープルクッキーです。缶もかわいいので喜んでいただけると思います。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p003", "ザ・メープルマニア グランスタ東京店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内"],
    budgetCategory: 3000,
  },
  {
    id: "p004",
    name: "東京鈴もなか",
    brand: "香炉庵 KOURO-AN",
    price: 320,
    priceLabel: "¥320（税込）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["東京駅銀の鈴モチーフ"],
    category: "和菓子",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦"],
    guaranteeReasons: [
      "東京駅の待ち合わせ場所「銀の鈴」をモチーフにした限定品",
      "甘さ控えめで年代を問わず渡しやすい",
      "個包装で配りやすい",
      "東京駅らしさが伝わる話題性",
      "手頃な価格で大量購入しやすい",
    ],
    guaranteeOneLiner: "東京駅「銀の鈴」モチーフの最中。話題性と手頃さを両立",
    makerQuote: "「東京駅の象徴である銀の鈴を、和菓子で表現しました」",
    makerStory: "グランスタ東京に出店する和菓子店。東京駅の銀の鈴をイメージした求肥餅入りもなかは、東京土産の定番として愛されている。",
    makerName: "香炉庵 和菓子職人",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。東京駅の銀の鈴をモチーフにしたもなかをお持ちしました。",
      thanks: "先日はありがとうございました。東京駅らしいお土産です。よろしければお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p004", "香炉庵 KOURO-AN グランスタ東京店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 1000,
  },
  {
    id: "p005",
    name: "ガレット ショコラ エピス",
    brand: "ピエール マルコリーニ",
    price: 3888,
    priceLabel: "¥3,888（税込）",
    imageUrl: IMG.chocolate,
    badges: ["editorial"],
    badgeLabels: ["ベルギー王室御用達"],
    category: "チョコレート",
    shelfLifeDays: 90,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦", "乳", "大豆"],
    guaranteeReasons: [
      "ベルギー王室御用達チョコレートブランド",
      "スパイスとチョコレートの絶妙な組み合わせ",
      "日持ち90日で余裕を持って渡せる",
      "高級感のあるパッケージで目上の方にも",
      "個包装で配りやすい",
    ],
    guaranteeOneLiner: "ベルギー王室御用達ブランドのガレット。目上の方への手土産に最適",
    makerQuote: "「チョコレートの可能性を、スパイスとの融合で広げています」",
    makerStory: "ベルギー王室御用達のチョコレートブランド。カカオ豆の産地から製造まで一貫管理し、世界最高水準のチョコレートを提供。",
    makerName: "ピエール マルコリーニ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。ベルギー王室御用達のチョコレートをお持ちしました。",
      thanks: "先日はありがとうございました。ピエール マルコリーニのガレットです。ぜひお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p005", "ピエール マルコリーニ グランスタ東京店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 5000,
  },
  {
    id: "p006",
    name: "フィナンシェ3種6個詰合わせ",
    brand: "ピエール・エルメ・パリ",
    price: 2592,
    priceLabel: "¥2,592（税込）",
    imageUrl: IMG.financier,
    badges: ["editorial"],
    badgeLabels: ["パリの名店 東京限定"],
    category: "焼き菓子",
    shelfLifeDays: 30,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳", "アーモンド"],
    guaranteeReasons: [
      "パリの名店ピエール・エルメの東京限定品",
      "ナチュール・イスパハン・ショコラの3種食べ比べ",
      "個包装で配りやすい",
      "グランスタ東京改札内で購入可能",
      "日持ち30日で余裕を持って渡せる",
    ],
    guaranteeOneLiner: "パリの名店の東京限定フィナンシェ。3種食べ比べが話題になる",
    makerQuote: "「フィナンシェは、シンプルな素材の中に複雑な美しさを宿しています」",
    makerStory: "世界的に有名なフランスのパティシエ、ピエール・エルメが手がけるブランド。東京グランスタ店では限定フレーバーを展開。",
    makerName: "ピエール・エルメ・パリ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。ピエール・エルメの東京限定フィナンシェをお持ちしました。",
      thanks: "先日はありがとうございました。パリの名店の限定品です。ぜひお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p006", "ピエール・エルメ・パリ グランスタ東京店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 3000,
  },
  {
    id: "p007",
    name: "キャラメルバターサンドイッチ",
    brand: "(NO) RAISIN SANDWICH",
    price: 1580,
    priceLabel: "¥1,580（税込）",
    imageUrl: IMG.sandwich,
    badges: ["editorial"],
    badgeLabels: ["フードディレクター監修"],
    category: "スイーツ",
    shelfLifeDays: 10,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "フードディレクター平野紗季子さんプロデュース",
      "ネットでもなかなか買えない希少品",
      "上質な素材と豊かな風味",
      "パッケージのくまがかわいくギフト向き",
      "個包装で配りやすい",
    ],
    guaranteeOneLiner: "フードディレクター監修の希少バターサンド。話題性で会話が弾む",
    makerQuote: "「レーズンなしでも、バターサンドはこんなに豊かになれる」",
    makerStory: "フードディレクター平野紗季子さんがプロデュースする新感覚バターサンド専門店。東京駅グランスタに出店し、連日完売が続く人気店。",
    makerName: "(NO) RAISIN SANDWICH",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。話題のバターサンドをお持ちしました。",
      thanks: "先日はありがとうございました。フードディレクター監修の希少なバターサンドです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p007", "(NO) RAISIN SANDWICH グランスタ東京店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "soldout_risk",
    purposes: ["挨拶", "御礼", "自分用"],
    budgetCategory: 2000,
  },
  {
    id: "p008",
    name: "フールセック50枚入",
    brand: "コロンバン",
    price: 4212,
    priceLabel: "¥4,212（税込）",
    imageUrl: IMG.cookie,
    badges: ["local"],
    badgeLabels: ["1924年創業 老舗"],
    category: "焼き菓子",
    shelfLifeDays: 120,
    individuallyWrapped: true,
    recommendedCount: 25,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳", "大豆", "りんご", "アーモンド"],
    guaranteeReasons: [
      "1924年創業の老舗洋菓子店",
      "8種類のフールセックが楽しめる",
      "日持ち120日で余裕を持って渡せる",
      "個包装で大人数への配布に最適",
      "東京駅グランスタ改札内で購入可能",
    ],
    guaranteeOneLiner: "1924年創業老舗の詰め合わせ。8種類の味で大人数への配布に最適",
    makerQuote: "「100年続く味は、素材への敬意と職人の技から生まれます」",
    makerStory: "1924年創業の老舗洋菓子店。日本初のフランス菓子専門店として、長年にわたり日本の洋菓子文化を牽引してきた。",
    makerName: "コロンバン",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。1924年創業のコロンバンのフールセックをお持ちしました。",
      thanks: "先日はありがとうございました。老舗コロンバンの詰め合わせです。ぜひお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p008", "コロンバン グランスタ東京店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "お詫び"],
    budgetCategory: 5000,
  },
  // ─────────────────────────────────────────────────────────────
  // 東京駅 東京ギフトパレット（改札外）
  // ─────────────────────────────────────────────────────────────
  {
    id: "p009",
    name: "バターミルフィユ",
    brand: "バターバトラー",
    price: 1620,
    priceLabel: "¥1,620（税込）",
    imageUrl: IMG.butter,
    badges: ["editorial"],
    badgeLabels: ["東京ギフトパレット限定"],
    category: "スイーツ",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "東京ギフトパレット限定商品",
      "ヨーロッパ産発酵バター使用",
      "サクサクのパイにバタークリームをサンド",
      "個包装でシェアしやすい",
      "手土産として見栄えが良い",
    ],
    guaranteeOneLiner: "発酵バター使用の限定ミルフィユ。バター好きへの手土産に",
    makerQuote: "「バターの豊かな香りと風味を、最高のミルフィユで届けたい」",
    makerStory: "東京ギフトパレットに出店するバタースイーツ専門店。ヨーロッパ産発酵バターにこだわり、毎日手作りで提供。",
    makerName: "バターバトラー パティシエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。東京駅限定のバターミルフィユをお持ちしました。",
      thanks: "先日はありがとうございました。発酵バター使用の限定品です。ぜひお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p009", "バターバトラー 東京ギフトパレット店", "改札外", "1F", 8)],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "自分用"],
    budgetCategory: 2000,
  },
  {
    id: "p010",
    name: "塩キャラメルのミルフィーユ",
    brand: "アマンド東京",
    price: 1350,
    priceLabel: "¥1,350（税込）",
    imageUrl: IMG.butter,
    badges: ["editorial"],
    badgeLabels: ["個包装で配りやすい"],
    category: "スイーツ",
    shelfLifeDays: 30,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳", "アーモンド"],
    guaranteeReasons: [
      "アーモンドが香るザクザク食感のパイ",
      "塩キャラメルとホワイトチョコクリームの組み合わせ",
      "レモンピールで上品な酸味をプラス",
      "個包装で配りやすい",
      "日持ち30日で余裕を持って渡せる",
    ],
    guaranteeOneLiner: "塩キャラメルとレモンピールの絶妙バランス。個包装で大人数配布に",
    makerQuote: "「甘さの中に塩気と酸味を加えることで、飽きのこない味わいを実現しました」",
    makerStory: "東京ギフトパレットに出店するスイーツブランド。アーモンドの香ばしさと塩キャラメルの組み合わせが人気。",
    makerName: "アマンド東京",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。塩キャラメルのミルフィーユをお持ちしました。",
      thanks: "先日はありがとうございました。個包装で配りやすいミルフィーユです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p010", "アマンド東京 東京ギフトパレット店", "改札外", "1F", 8)],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 2000,
  },
  {
    id: "p011",
    name: "イチゴミルクサンド",
    brand: "イチゴショップ by FRANCAIS",
    price: 1296,
    priceLabel: "¥1,296（税込）",
    imageUrl: IMG.sandwich,
    badges: ["editorial"],
    badgeLabels: ["ばらまき用に最適"],
    category: "スイーツ",
    shelfLifeDays: 20,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "イチゴとラズベリーの果物感が強い",
      "練乳入りクッキーのやさしい甘さ",
      "かわいらしいデザインの個包装",
      "ばらまき用お土産として重宝",
      "東京ギフトパレット限定品",
    ],
    guaranteeOneLiner: "イチゴ＆ラズベリーの果実感たっぷり。かわいい個包装でばらまきに",
    makerQuote: "「イチゴの甘酸っぱさを、クッキーサンドで表現しました」",
    makerStory: "東京ギフトパレットに出店するイチゴスイーツ専門店。果物の風味を最大限に活かした商品作りにこだわる。",
    makerName: "イチゴショップ by FRANCAIS",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。イチゴミルクサンドをお持ちしました。",
      thanks: "先日はありがとうございました。かわいいイチゴのサンドクッキーです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p011", "イチゴショップ by FRANCAIS 東京ギフトパレット店", "改札外", "1F", 8)],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "社内", "差し入れ"],
    budgetCategory: 2000,
  },
  {
    id: "p012",
    name: "サクッチ・ホロッチ＜ティラミス＞",
    brand: "シーキューブ TIRAMISÙ",
    price: 648,
    priceLabel: "¥648（税込）",
    imageUrl: IMG.cake,
    badges: ["editorial"],
    badgeLabels: ["東京駅限定 ティラミス専門店"],
    category: "スイーツ",
    shelfLifeDays: 30,
    individuallyWrapped: false,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "乳"],
    guaranteeReasons: [
      "2024年オープンのティラミス専門店",
      "北海道マスカルポーネチーズパウダー使用",
      "コーヒー風味のチョコレートでティラミスを表現",
      "東京駅限定商品",
      "手頃な価格で気軽に渡せる",
    ],
    guaranteeOneLiner: "ティラミス専門店の東京駅限定焼き菓子。話題性と手頃さが魅力",
    makerQuote: "「ティラミスの美味しさを、焼き菓子で持ち歩けるようにしました」",
    makerStory: "2024年に東京ギフトパレットにオープンしたティラミス専門店。北海道産マスカルポーネを使用した本格的な味わいが人気。",
    makerName: "シーキューブ TIRAMISÙ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。東京駅限定のティラミス焼き菓子をお持ちしました。",
      thanks: "先日はありがとうございました。ティラミス専門店の限定品です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p012", "シーキューブ TIRAMISÙ 東京ギフトパレット店", "改札外", "1F", 8)],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["差し入れ", "自分用", "社内"],
    budgetCategory: 1000,
  },
  // ─────────────────────────────────────────────────────────────
  // 羽田空港（第1・第2ターミナル）
  // ─────────────────────────────────────────────────────────────
  {
    id: "p013",
    name: "Hanegumo（はねぐも）",
    brand: "叶匠壽庵",
    price: 1188,
    priceLabel: "¥1,188（税込）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["羽田空港限定 雲型どら焼き"],
    category: "和菓子",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "羽田空港限定のふわふわ雲型どら焼き",
      "北海道産小豆使用の上品な甘さ",
      "日本茶にもコーヒーにも合う",
      "リピーターが多い人気商品",
      "個包装で配りやすい",
    ],
    guaranteeOneLiner: "羽田空港限定の雲型どら焼き。ふわふわ食感でリピーター続出",
    makerQuote: "「空を飛ぶ雲のように、ふわふわとした食感を大切にしています」",
    makerStory: "滋賀県に本店を構える老舗和菓子店・叶匠壽庵の羽田空港限定品。北海道産小豆を使用した上品な甘さが特徴。",
    makerName: "叶匠壽庵 和菓子職人",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。羽田空港限定のはねぐもをお持ちしました。",
      thanks: "先日はありがとうございました。羽田空港でしか買えないどら焼きです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      hanetaSeller("s_p013a", "叶匠壽庵 PIER1", "haneda_t1", "改札外"),
      hanetaSeller("s_p013b", "叶匠壽庵 PIER2", "haneda_t2", "改札外"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 2000,
  },
  {
    id: "p014",
    name: "バターサンド",
    brand: "PRESS BUTTER SAND",
    price: 1215,
    priceLabel: "¥1,215（税込）",
    imageUrl: IMG.butter,
    badges: ["editorial"],
    badgeLabels: ["全国区の人気ブランド"],
    category: "スイーツ",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "バタークリームとバターキャラメルの2層サンド",
      "サクサクのクッキー生地",
      "全国的に人気の定番ブランド",
      "個包装で配りやすい",
      "羽田空港・東京駅など複数施設で購入可能",
    ],
    guaranteeOneLiner: "全国人気のバターサンド。羽田空港・東京駅両方で購入できる定番品",
    makerQuote: "「バターの濃厚な風味を、最高のサンドクッキーで届けたい」",
    makerStory: "全国の主要駅・空港に展開するバタースイーツ専門店。北海道産バターを使用した濃厚な味わいが人気の秘密。",
    makerName: "PRESS BUTTER SAND",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。PRESS BUTTER SANDのバターサンドをお持ちしました。",
      thanks: "先日はありがとうございました。全国で人気のバターサンドです。ぜひお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      hanetaSeller("s_p014a", "PRESS BUTTER SAND 羽田T1 特選洋菓子館", "haneda_t1", "改札外"),
      hanetaSeller("s_p014b", "PRESS BUTTER SAND 羽田T2", "haneda_t2", "改札外"),
      tokyoSeller("s_p014c", "PRESS BUTTER SAND グランスタ東京店", "改札内"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 2000,
  },
  {
    id: "p015",
    name: "レーズンサンド",
    brand: "小川軒",
    price: 1728,
    priceLabel: "¥1,728（税込）",
    imageUrl: IMG.sandwich,
    badges: ["local"],
    badgeLabels: ["羽田空港 保安検査場内"],
    category: "スイーツ",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "洋酒漬けレーズンとクリームの絶妙バランス",
      "羽田空港保安検査場内で購入可能",
      "しっとりクッキーとジューシーレーズン",
      "個包装で配りやすい",
      "大人の手土産として定評あり",
    ],
    guaranteeOneLiner: "羽田空港保安検査場内で買える老舗のレーズンサンド。大人の手土産に",
    makerQuote: "「洋酒に漬け込んだレーズンの豊かな風味を、クッキーサンドで表現しました」",
    makerStory: "東京の老舗洋菓子店・小川軒。羽田空港の保安検査場内に出店し、出発前の最後のお土産購入に便利。",
    makerName: "小川軒",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。小川軒のレーズンサンドをお持ちしました。",
      thanks: "先日はありがとうございました。老舗小川軒のレーズンサンドです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [hanetaSeller("s_p015", "小川軒 JAL PLAZA ゲートショップ", "haneda_t1", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 2000,
  },
  {
    id: "p016",
    name: "グレイシア",
    brand: "AUDREY",
    price: 1296,
    priceLabel: "¥1,296（税込）",
    imageUrl: IMG.macaron,
    badges: ["editorial"],
    badgeLabels: ["花束のようなスイーツ"],
    category: "スイーツ",
    shelfLifeDays: 14,
    individuallyWrapped: false,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "乳"],
    guaranteeReasons: [
      "花束のような可愛らしい見た目",
      "ミルキーなクリームと甘酸っぱいイチゴ",
      "チュイールで包んだ一口サイズ",
      "SNS映えするビジュアル",
      "女性へのプレゼントに最適",
    ],
    guaranteeOneLiner: "花束のような見た目のスイーツ。女性へのプレゼントに間違いなし",
    makerQuote: "「食べる前から笑顔になれる、花束のようなスイーツを作りました」",
    makerStory: "東京の人気スイーツブランドAUDREY。花束をモチーフにした可愛らしいパッケージと、繊細な味わいが女性を中心に人気。",
    makerName: "AUDREY パティシエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。AUDREYのグレイシアをお持ちしました。",
      thanks: "先日はありがとうございました。花束のようなかわいいスイーツです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      hanetaSeller("s_p016a", "AUDREY 羽田T1 特選洋菓子館", "haneda_t1", "改札外"),
      hanetaSeller("s_p016b", "AUDREY 羽田T2", "haneda_t2", "改札外"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "自分用"],
    budgetCategory: 2000,
  },
  {
    id: "p017",
    name: "N.Y.キャラメルサンド",
    brand: "NYCSAND",
    price: 756,
    priceLabel: "¥756（税込）",
    imageUrl: IMG.sandwich,
    badges: ["editorial"],
    badgeLabels: ["羽田空港限定デザイン"],
    category: "スイーツ",
    shelfLifeDays: 30,
    individuallyWrapped: true,
    recommendedCount: 4,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "羽田空港限定デザインの4個入りセット",
      "とろとろキャラメルをチョコレートで包む",
      "香ばしいクッキーでサンド",
      "手頃な価格で気軽に渡せる",
      "個包装で配りやすい",
    ],
    guaranteeOneLiner: "羽田空港限定デザインのキャラメルサンド。手頃な価格で気軽に渡せる",
    makerQuote: "「ニューヨークのキャラメルの豊かな甘さを、クッキーサンドで表現しました」",
    makerStory: "NYスタイルのキャラメルサンド専門店。羽田空港限定デザインは出張帰りのお土産として人気。",
    makerName: "NYCSAND",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。羽田空港限定のキャラメルサンドをお持ちしました。",
      thanks: "先日はありがとうございました。羽田空港限定デザインのキャラメルサンドです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      hanetaSeller("s_p017a", "NYCSAND 羽田T1 東京食賓館", "haneda_t1", "改札外"),
      hanetaSeller("s_p017b", "NYCSAND 羽田T2", "haneda_t2", "改札外"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["差し入れ", "社内", "自分用"],
    budgetCategory: 1000,
  },
  {
    id: "p018",
    name: "芋きん",
    brand: "浅草満願堂",
    price: 183,
    priceLabel: "¥183（税込）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["浅草名物 日持ち30日"],
    category: "和菓子",
    shelfLifeDays: 30,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦"],
    guaranteeReasons: [
      "浅草名物の定番和菓子",
      "さつまいも皮の生地で焼き芋餡を包む",
      "日持ち30日で余裕を持って渡せる",
      "個包装で配りやすい",
      "手頃な価格で大量購入しやすい",
    ],
    guaranteeOneLiner: "浅草名物の芋きん。日持ち30日・個包装で大人数配布に最適",
    makerQuote: "「さつまいもの素朴な甘さを、職人の技で最高の和菓子に仕上げました」",
    makerStory: "浅草に本店を構える老舗和菓子店・浅草満願堂。さつまいもを使った和菓子専門店として、地元民から観光客まで幅広く愛されている。",
    makerName: "浅草満願堂 和菓子職人",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。浅草名物の芋きんをお持ちしました。",
      thanks: "先日はありがとうございました。浅草の老舗和菓子店の芋きんです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      hanetaSeller("s_p018a", "浅草満願堂 PIER5", "haneda_t1", "改札外"),
      hanetaSeller("s_p018b", "浅草満願堂 羽田T2", "haneda_t2", "改札外"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["社内", "差し入れ", "自分用"],
    budgetCategory: 1000,
  },
  {
    id: "p019",
    name: "御用邸チーズケーキ",
    brand: "チーズガーデン",
    price: 1680,
    priceLabel: "¥1,680（税込）",
    imageUrl: IMG.cheese,
    badges: ["editorial"],
    badgeLabels: ["保安検査場内で購入可能"],
    category: "スイーツ",
    shelfLifeDays: 14,
    individuallyWrapped: false,
    recommendedCount: 5,
    temperature: "冷蔵",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "羽田空港保安検査場内で購入可能",
      "しっとり濃厚なチーズの味わい",
      "後味さっぱりでフレッシュなミルクの余韻",
      "チーズケーキの定番ブランド",
      "贈り物として定評あり",
    ],
    guaranteeOneLiner: "保安検査場内で買える濃厚チーズケーキ。出発直前まで購入可能",
    makerQuote: "「那須の豊かな自然が育んだチーズの美味しさを、ケーキで表現しました」",
    makerStory: "栃木県那須に本店を構えるチーズガーデン。羽田空港の保安検査場内に出店し、出発直前まで購入できる利便性が高い。",
    makerName: "チーズガーデン",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。チーズガーデンの御用邸チーズケーキをお持ちしました。",
      thanks: "先日はありがとうございました。那須の人気チーズケーキです。ぜひお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [hanetaSeller("s_p019", "チーズガーデン JAL PLAZA保安検査場内", "haneda_t1", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "自分用"],
    budgetCategory: 2000,
  },
  {
    id: "p020",
    name: "ベイクドショコラガトーラスク",
    brand: "La Terre",
    price: 1296,
    priceLabel: "¥1,296（税込）",
    imageUrl: IMG.rusk,
    badges: ["local"],
    badgeLabels: ["羽田空港限定品"],
    category: "スイーツ",
    shelfLifeDays: 30,
    individuallyWrapped: false,
    recommendedCount: 8,
    temperature: "常温",
    allergens: ["小麦", "乳"],
    guaranteeReasons: [
      "羽田空港限定のガトーショコラ風ラスク",
      "クーベルチュールチョコレートと北海道産発酵バター使用",
      "世田谷三宿の人気洋菓子店の味",
      "日持ち30日で余裕を持って渡せる",
      "羽田空港でしか買えない限定品",
    ],
    guaranteeOneLiner: "羽田空港限定のガトーショコララスク。世田谷の人気店の味が空港で",
    makerQuote: "「ガトーショコラの濃厚な味わいを、ラスクで手軽に楽しんでほしい」",
    makerStory: "世田谷区三宿に本店を構える人気洋菓子店・ラ・テール。羽田空港限定品は空港でしか買えない特別な一品。",
    makerName: "La Terre パティシエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。羽田空港限定のガトーショコララスクをお持ちしました。",
      thanks: "先日はありがとうございました。羽田空港でしか買えない限定品です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      hanetaSeller("s_p020a", "La Terre 羽田T1 PIER1", "haneda_t1", "改札外"),
      hanetaSeller("s_p020b", "La Terre 羽田T2", "haneda_t2", "改札外"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 2000,
  },
  // ─────────────────────────────────────────────────────────────
  // 品川駅（エキュート品川・アトレ品川）
  // ─────────────────────────────────────────────────────────────
  {
    id: "p021",
    name: "ブラウンチーズブラザー プレーン",
    brand: "BROWN CHEESE BROTHER",
    price: 972,
    priceLabel: "¥972（税込）",
    imageUrl: IMG.cheese,
    badges: ["editorial"],
    badgeLabels: ["エキュート品川 改札内"],
    category: "焼き菓子",
    shelfLifeDays: 30,
    individuallyWrapped: false,
    recommendedCount: 3,
    temperature: "常温",
    allergens: ["小麦", "乳"],
    guaranteeReasons: [
      "ホエイを煮詰めたブラウンチーズ使用",
      "甘酸っぱく濃厚な味わい",
      "チーズが苦手な方にもおすすめ",
      "エキュート品川改札内で購入可能",
      "日持ち30日で余裕を持って渡せる",
    ],
    guaranteeOneLiner: "ブラウンチーズのガレットサンド。チーズ好きへの手土産に最適",
    makerQuote: "「ブラウンチーズの独特の甘酸っぱさを、ガレット生地で引き立てました」",
    makerStory: "品川駅エキュートに出店するチーズスイーツ専門店。北欧のブラウンチーズを使った珍しいサンドクッキーが人気。",
    makerName: "BROWN CHEESE BROTHER",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。ブラウンチーズのサンドクッキーをお持ちしました。",
      thanks: "先日はありがとうございました。珍しいブラウンチーズのクッキーです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinagawaSeller("s_p021", "BROWN CHEESE BROTHER エキュート品川店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "自分用"],
    budgetCategory: 1000,
  },
  {
    id: "p022",
    name: "あげもち（塩）",
    brand: "御門屋",
    price: 420,
    priceLabel: "¥420（税込）",
    imageUrl: IMG.snack,
    badges: ["local"],
    badgeLabels: ["創業50年以上 宮城産もち米"],
    category: "和菓子・米菓",
    shelfLifeDays: 70,
    individuallyWrapped: false,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["大豆"],
    guaranteeReasons: [
      "創業50年以上の老舗揚げもち専門店",
      "宮城県産最高級もち米「みやこがね」使用",
      "サクサクとした軽い食感と程よい塩味",
      "日持ち70日で余裕を持って渡せる",
      "エキュート品川改札内で購入可能",
    ],
    guaranteeOneLiner: "50年以上の老舗の揚げもち。宮城産最高級もち米使用で日持ち70日",
    makerQuote: "「最高級のもち米を使い、職人が一つ一つ丁寧に揚げています」",
    makerStory: "品川駅エキュートに出店する老舗揚げもち専門店。宮城県産最高級もち米を使用し、50年以上変わらない味を守り続けている。",
    makerName: "御門屋 職人",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。老舗御門屋のあげもちをお持ちしました。",
      thanks: "先日はありがとうございました。50年以上の老舗の揚げもちです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinagawaSeller("s_p022", "御門屋 エキュート品川店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["差し入れ", "社内", "自分用"],
    budgetCategory: 1000,
  },
  {
    id: "p023",
    name: "はちみつフィナンシェ",
    brand: "パティスリーQBG",
    price: 1700,
    priceLabel: "¥1,700（税込）",
    imageUrl: IMG.financier,
    badges: ["editorial"],
    badgeLabels: ["はちみつメーカー直営"],
    category: "焼き菓子",
    shelfLifeDays: 21,
    individuallyWrapped: false,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳", "アーモンド"],
    guaranteeReasons: [
      "はちみつメーカー直営店のフィナンシェ",
      "ウクライナ産ひまわりはちみつとメキシコ産オレンジはちみつをブレンド",
      "外はカリッと、中はしっとりもちもち",
      "エキュート品川改札内で購入可能",
      "はちみつの豊かな香りが特徴",
    ],
    guaranteeOneLiner: "はちみつ専門メーカー直営のフィナンシェ。2種のはちみつブレンドが絶品",
    makerQuote: "「世界最高のはちみつを使った、究極のフィナンシェを目指しています」",
    makerStory: "品川駅エキュートに出店するはちみつメーカー直営のパティスリー。ウクライナ産とメキシコ産の2種のはちみつをブレンドした特製フィナンシェが人気。",
    makerName: "パティスリーQBG パティシエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。はちみつメーカー直営のフィナンシェをお持ちしました。",
      thanks: "先日はありがとうございました。こだわりのはちみつを使ったフィナンシェです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinagawaSeller("s_p023", "パティスリーQBG エキュート品川店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 2000,
  },
  {
    id: "p024",
    name: "ごまたまご",
    brand: "銀座たまや",
    price: 486,
    priceLabel: "¥486（税込）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["和洋折衷 幅広い年代に人気"],
    category: "焼き菓子",
    shelfLifeDays: 21,
    individuallyWrapped: true,
    recommendedCount: 3,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "可愛らしい卵型の焼き菓子",
      "黒ごまペーストと黒ごま餡をカステラ生地で包む",
      "ホワイトチョコレートでコーティング",
      "和洋折衷の味わいで幅広い年代に人気",
      "個包装で配りやすい",
    ],
    guaranteeOneLiner: "卵型の可愛い和洋折衷菓子。幅広い年代に喜ばれる手頃な手土産",
    makerQuote: "「和と洋の良さを組み合わせた、新しい東京土産を作りました」",
    makerStory: "品川駅エキュートに出店する和洋菓子店。黒ごまの香ばしさとホワイトチョコの甘さが絶妙にマッチした人気商品。",
    makerName: "銀座たまや",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。ごまたまごをお持ちしました。",
      thanks: "先日はありがとうございました。可愛い卵型の和洋菓子です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinagawaSeller("s_p024", "銀座たまや エキュート品川店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["差し入れ", "社内", "自分用"],
    budgetCategory: 1000,
  },
  {
    id: "p025",
    name: "東京キャラメリゼ",
    brand: "上野風月堂",
    price: 648,
    priceLabel: "¥648（税込）",
    imageUrl: IMG.rusk,
    badges: ["local"],
    badgeLabels: ["1747年創業 老舗"],
    category: "焼き菓子",
    shelfLifeDays: 30,
    individuallyWrapped: false,
    recommendedCount: 12,
    temperature: "常温",
    allergens: ["小麦", "乳"],
    guaranteeReasons: [
      "1747年創業の老舗上野風月堂が開発",
      "薄焼きウエハースにキャラメリゼをコーティング",
      "サクサクとした軽い食感",
      "品川駅改札内の複数店舗で購入可能",
      "手頃な価格で気軽に渡せる",
    ],
    guaranteeOneLiner: "1747年創業老舗の新東京土産。品川駅改札内で手軽に購入できる",
    makerQuote: "「江戸時代から続く老舗が、新しい東京土産を作りました」",
    makerStory: "1747年創業の老舗洋菓子店・上野風月堂。品川駅構内の複数店舗に出店し、出張帰りのビジネスパーソンに愛されている。",
    makerName: "上野風月堂",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。1747年創業の上野風月堂のキャラメリゼをお持ちしました。",
      thanks: "先日はありがとうございました。老舗風月堂の新東京土産です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinagawaSeller("s_p025", "上野風月堂 グランスタ品川店", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["差し入れ", "社内", "自分用"],
    budgetCategory: 1000,
  },
  // ─────────────────────────────────────────────────────────────
  // 新宿駅周辺（伊勢丹・ニュウマン・高島屋）
  // ─────────────────────────────────────────────────────────────
  {
    id: "p026",
    name: "鳩サブレー 新宿伊勢丹店限定缶",
    brand: "鎌倉 豊島屋",
    price: 2160,
    priceLabel: "¥2,160（税込）",
    imageUrl: IMG.cookie,
    badges: ["local"],
    badgeLabels: ["鎌倉の名物 新宿限定缶"],
    category: "クッキー",
    shelfLifeDays: 60,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "鎌倉土産の定番・鳩サブレーの新宿限定缶",
      "バターの豊かな香りと風味",
      "日持ち60日以上で余裕を持って渡せる",
      "限定缶が話題になる",
      "個包装で配りやすい",
    ],
    guaranteeOneLiner: "鎌倉の名物・鳩サブレーの新宿限定缶。定番の安心感と限定の話題性",
    makerQuote: "「鎌倉の鳩サブレーを、新宿でも楽しんでいただきたい」",
    makerStory: "鎌倉に本店を構える老舗菓子店・豊島屋。鳩サブレーは鎌倉土産の定番として全国的に知られており、新宿伊勢丹限定缶は特別な一品。",
    makerName: "鎌倉 豊島屋",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。鎌倉の鳩サブレーの新宿限定缶をお持ちしました。",
      thanks: "先日はありがとうございました。鳩サブレーの新宿限定缶です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinjukuSeller("s_p026", "鎌倉 豊島屋 伊勢丹新宿店", "改札外")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内"],
    budgetCategory: 3000,
  },
  {
    id: "p027",
    name: "バターのいとこ ミルク味",
    brand: "バターのいとこ",
    price: 1080,
    priceLabel: "¥1,080（税込）",
    imageUrl: IMG.butter,
    badges: ["editorial"],
    badgeLabels: ["那須の牛乳使用"],
    category: "スイーツ",
    shelfLifeDays: 30,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "乳"],
    guaranteeReasons: [
      "那須の新鮮な牛乳を使用",
      "ワッフル生地にミルクあんをサンド",
      "個包装で配りやすい",
      "新宿ルミネエスト店で購入可能",
      "日持ち30日で余裕を持って渡せる",
    ],
    guaranteeOneLiner: "那須の牛乳使用のバター菓子。ミルクの豊かな風味が人気の秘密",
    makerQuote: "「那須の豊かな自然が育んだ牛乳の美味しさを、お菓子で届けたい」",
    makerStory: "栃木県那須に本店を構えるバタースイーツブランド。那須の新鮮な牛乳を使用したワッフルサンドが人気。",
    makerName: "バターのいとこ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。那須の牛乳を使ったバターのいとこをお持ちしました。",
      thanks: "先日はありがとうございました。那須の牛乳使用のバター菓子です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinjukuSeller("s_p027", "バターのいとこ ルミネエスト新宿店", "改札外", "ルミネエスト新宿")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 2000,
  },
  {
    id: "p028",
    name: "ふゆうじょん",
    brand: "和菓子 結",
    price: 1620,
    priceLabel: "¥1,620（税込）",
    imageUrl: IMG.wagashi,
    badges: ["editorial"],
    badgeLabels: ["ニュウマン新宿 改札内"],
    category: "和菓子",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵"],
    guaranteeReasons: [
      "ニュウマン新宿改札内で購入可能",
      "現代的なデザインの和菓子",
      "個包装で配りやすい",
      "新宿駅直結で便利",
      "和菓子の新しい形を提案",
    ],
    guaranteeOneLiner: "新宿駅改札内で買える現代和菓子。個包装で手土産に最適",
    makerQuote: "「伝統的な和菓子を、現代のライフスタイルに合わせて再解釈しました」",
    makerStory: "ニュウマン新宿に出店する現代和菓子店。伝統的な和菓子の技法を活かしながら、現代的なデザインと味わいを追求。",
    makerName: "和菓子 結",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。和菓子 結のふゆうじょんをお持ちしました。",
      thanks: "先日はありがとうございました。新宿駅改札内で買える現代和菓子です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinjukuSeller("s_p028", "和菓子 結 ニュウマン新宿店", "改札内", "ニュウマン新宿")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 2000,
  },
  {
    id: "p029",
    name: "新宿高島屋限定 冨貴寄 お江戸の薔薇",
    brand: "銀座 菊廼舎",
    price: 1242,
    priceLabel: "¥1,242（税込）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["1890年創業 新宿高島屋限定"],
    category: "和菓子",
    shelfLifeDays: 60,
    individuallyWrapped: false,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "卵"],
    guaranteeReasons: [
      "1890年創業の老舗・銀座菊廼舎の限定品",
      "色とりどりの干菓子が楽しめる",
      "新宿高島屋限定デザイン",
      "日持ち60日以上で余裕を持って渡せる",
      "目上の方への手土産に最適",
    ],
    guaranteeOneLiner: "1890年創業老舗の新宿高島屋限定品。目上の方への手土産に格調高い",
    makerQuote: "「江戸時代から続く伝統の干菓子を、現代に伝え続けています」",
    makerStory: "1890年創業の老舗和菓子店・銀座菊廼舎。冨貴寄は代表銘菓として知られ、新宿高島屋限定デザインは特別な手土産として人気。",
    makerName: "銀座 菊廼舎",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。1890年創業の銀座菊廼舎の冨貴寄をお持ちしました。",
      thanks: "先日はありがとうございました。老舗菊廼舎の新宿高島屋限定品です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shinjukuSeller("s_p029", "銀座 菊廼舎 新宿高島屋店", "改札外", "新宿高島屋")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 2000,
  },
  {
    id: "p030",
    name: "ソルト＆カマンベールクッキー",
    brand: "東京ミルクチーズ工場",
    price: 1296,
    priceLabel: "¥1,296（税込）",
    imageUrl: IMG.cheese,
    badges: ["editorial"],
    badgeLabels: ["チーズ専門店の定番品"],
    category: "クッキー",
    shelfLifeDays: 45,
    individuallyWrapped: true,
    recommendedCount: 8,
    temperature: "常温",
    allergens: ["小麦", "乳"],
    guaranteeReasons: [
      "チーズ専門店ならではの本格的な風味",
      "塩とカマンベールチーズの絶妙な組み合わせ",
      "個包装で配りやすい",
      "新宿・渋谷など複数施設で購入可能",
      "日持ち45日で余裕を持って渡せる",
    ],
    guaranteeOneLiner: "チーズ専門店の定番クッキー。塩とカマンベールの絶妙バランス",
    makerQuote: "「チーズの豊かな風味を、クッキーで手軽に楽しんでほしい」",
    makerStory: "東京を代表するチーズスイーツ専門店。新宿・渋谷など複数の駅ビルに出店し、チーズ好きの間で定番のお土産として知られている。",
    makerName: "東京ミルクチーズ工場",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。東京ミルクチーズ工場のクッキーをお持ちしました。",
      thanks: "先日はありがとうございました。チーズ専門店の定番クッキーです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      shinjukuSeller("s_p030a", "東京ミルクチーズ工場 ルミネエスト新宿店", "改札外", "ルミネエスト新宿"),
      shibuyaSeller("s_p030b", "東京ミルクチーズ工場 渋谷マークシティ店", "改札外", "渋谷マークシティ"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 2000,
  },
  // ─────────────────────────────────────────────────────────────
  // 渋谷駅周辺（渋谷スクランブルスクエア・ヒカリエ・マークシティ）
  // ─────────────────────────────────────────────────────────────
  {
    id: "p031",
    name: "バターサンド〈チョコレート〉",
    brand: "PRESS BUTTER SAND",
    price: 1215,
    priceLabel: "¥1,215（税込）",
    imageUrl: IMG.chocolate,
    badges: ["editorial"],
    badgeLabels: ["渋谷スクランブルスクエア"],
    category: "スイーツ",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "チョコレートフレーバーの限定バターサンド",
      "渋谷スクランブルスクエアで購入可能",
      "全国的に人気のブランド",
      "個包装で配りやすい",
      "チョコ好きへの手土産に最適",
    ],
    guaranteeOneLiner: "全国人気ブランドのチョコレートバターサンド。渋谷スクランブルスクエアで購入",
    makerQuote: "「バターとチョコレートの最高の組み合わせを追求しました」",
    makerStory: "全国の主要駅・商業施設に展開するバタースイーツ専門店。渋谷スクランブルスクエア店ではチョコレートフレーバーも展開。",
    makerName: "PRESS BUTTER SAND",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。PRESS BUTTER SANDのチョコレートバターサンドをお持ちしました。",
      thanks: "先日はありがとうございました。全国人気のバターサンドのチョコレートフレーバーです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shibuyaSeller("s_p031", "PRESS BUTTER SAND 渋谷スクランブルスクエア店", "改札外")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 2000,
  },
  {
    id: "p032",
    name: "カヌレ・エシレ",
    brand: "エシレ・パティスリー オ ブール",
    price: 2160,
    priceLabel: "¥2,160（税込）",
    imageUrl: IMG.cake,
    badges: ["editorial"],
    badgeLabels: ["フランス王室御用達バター使用"],
    category: "スイーツ",
    shelfLifeDays: 3,
    individuallyWrapped: false,
    recommendedCount: 4,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "フランス王室御用達エシレバター使用",
      "外はカリッと中はとろりの本格カヌレ",
      "渋谷スクランブルスクエアで購入可能",
      "フランス菓子の最高峰ブランド",
      "特別な手土産として話題になる",
    ],
    guaranteeOneLiner: "フランス王室御用達バター使用の本格カヌレ。特別な手土産に最適",
    makerQuote: "「エシレバターの豊かな風味を、カヌレで最大限に引き出しています」",
    makerStory: "フランス王室御用達のエシレバターを使用したパティスリー。渋谷スクランブルスクエアに出店し、本格フランス菓子を提供。",
    makerName: "エシレ・パティスリー オ ブール",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。エシレバター使用のカヌレをお持ちしました。",
      thanks: "先日はありがとうございました。フランス王室御用達バター使用の本格カヌレです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shibuyaSeller("s_p032", "エシレ・パティスリー オ ブール 渋谷スクランブルスクエア店", "改札外")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "soldout_risk",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 3000,
  },
  {
    id: "p033",
    name: "渋谷えびせんべい",
    brand: "桂新堂",
    price: 1080,
    priceLabel: "¥1,080（税込）",
    imageUrl: IMG.snack,
    badges: ["local"],
    badgeLabels: ["渋谷ヒカリエ 老舗えびせんべい"],
    category: "スナック",
    shelfLifeDays: 60,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["えび", "小麦"],
    guaranteeReasons: [
      "老舗えびせんべい専門店の定番品",
      "渋谷ヒカリエで購入可能",
      "日持ち60日以上で余裕を持って渡せる",
      "個包装で配りやすい",
      "幅広い年代に喜ばれる定番品",
    ],
    guaranteeOneLiner: "老舗えびせんべい専門店の定番品。日持ち60日で大人数配布に最適",
    makerQuote: "「えびの豊かな風味を、最高のせんべいで表現しています」",
    makerStory: "名古屋に本店を構える老舗えびせんべい専門店・桂新堂。渋谷ヒカリエに出店し、東京土産としても人気。",
    makerName: "桂新堂",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。老舗桂新堂のえびせんべいをお持ちしました。",
      thanks: "先日はありがとうございました。老舗のえびせんべいです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shibuyaSeller("s_p033", "桂新堂 渋谷ヒカリエ店", "改札外", "渋谷ヒカリエ")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["社内", "差し入れ", "挨拶"],
    budgetCategory: 2000,
  },
  {
    id: "p034",
    name: "マカロン",
    brand: "ピエール・エルメ・パリ",
    price: 2700,
    priceLabel: "¥2,700（税込）",
    imageUrl: IMG.macaron,
    badges: ["editorial"],
    badgeLabels: ["パリの名店 渋谷ヒカリエ"],
    category: "スイーツ",
    shelfLifeDays: 5,
    individuallyWrapped: false,
    recommendedCount: 6,
    temperature: "冷蔵",
    allergens: ["卵", "乳", "アーモンド"],
    guaranteeReasons: [
      "世界的に有名なパリの名店",
      "色鮮やかで見た目も美しい",
      "渋谷ヒカリエで購入可能",
      "女性へのプレゼントに最適",
      "フランス菓子の最高峰",
    ],
    guaranteeOneLiner: "パリの名店のマカロン。渋谷ヒカリエで購入できる本格フランス菓子",
    makerQuote: "「マカロンは、色と味と食感の三位一体の芸術です」",
    makerStory: "世界的に有名なフランスのパティシエ、ピエール・エルメが手がけるブランド。渋谷ヒカリエ店では季節限定フレーバーも展開。",
    makerName: "ピエール・エルメ・パリ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。ピエール・エルメのマカロンをお持ちしました。",
      thanks: "先日はありがとうございました。パリの名店のマカロンです。ぜひお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shibuyaSeller("s_p034", "ピエール・エルメ・パリ 渋谷ヒカリエ店", "改札外", "渋谷ヒカリエ")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び", "自分用"],
    budgetCategory: 3000,
  },
  {
    id: "p035",
    name: "豆大福",
    brand: "銀座甘楽",
    price: 1080,
    priceLabel: "¥1,080（税込）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["渋谷スクランブルスクエア 和菓子"],
    category: "和菓子",
    shelfLifeDays: 2,
    individuallyWrapped: false,
    recommendedCount: 4,
    temperature: "常温",
    allergens: ["小麦"],
    guaranteeReasons: [
      "銀座の老舗和菓子店の豆大福",
      "渋谷スクランブルスクエアで購入可能",
      "もちもちとした食感と上品な甘さ",
      "和菓子好きへの手土産に最適",
      "当日中に食べる特別感が喜ばれる",
    ],
    guaranteeOneLiner: "銀座老舗の豆大福。渋谷スクランブルスクエアで買える本格和菓子",
    makerQuote: "「毎朝手作りする豆大福の、もちもちとした食感を大切にしています」",
    makerStory: "銀座に本店を構える老舗和菓子店・銀座甘楽。渋谷スクランブルスクエアに出店し、毎朝手作りの豆大福を提供。",
    makerName: "銀座甘楽",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。銀座甘楽の豆大福をお持ちしました。",
      thanks: "先日はありがとうございました。銀座老舗の豆大福です。当日中にお召し上がりください。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [shibuyaSeller("s_p035", "銀座甘楽 渋谷スクランブルスクエア店", "改札外")],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "自分用"],
    budgetCategory: 2000,
  },
  // ─────────────────────────────────────────────────────────────
  // 複数施設対応・定番ブランド
  // ─────────────────────────────────────────────────────────────
  {
    id: "p036",
    name: "フィナンシェ",
    brand: "アンリ・シャルパンティエ",
    price: 897,
    priceLabel: "¥897（税込）",
    imageUrl: IMG.financier,
    badges: ["editorial"],
    badgeLabels: ["2種アーモンド使用 日持ち42日"],
    category: "焼き菓子",
    shelfLifeDays: 42,
    individuallyWrapped: true,
    recommendedCount: 5,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳", "アーモンド"],
    guaranteeReasons: [
      "2種のカリフォルニア産アーモンドをブレンド",
      "北海道産バターの芳醇な香り",
      "香料不使用の自然な風味",
      "日持ち42日で余裕を持って渡せる",
      "個包装で配りやすい",
    ],
    guaranteeOneLiner: "2種のアーモンドと北海道産バターのフィナンシェ。香料不使用で安心",
    makerQuote: "「最高の素材を、最高の技術で仕上げることが私たちの使命です」",
    makerStory: "フランス菓子の名店・アンリ・シャルパンティエ。2種のアーモンドと北海道産バターを使用した本格フィナンシェは、定番の手土産として全国で愛されている。",
    makerName: "アンリ・シャルパンティエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。アンリ・シャルパンティエのフィナンシェをお持ちしました。",
      thanks: "先日はありがとうございました。2種のアーモンドを使った本格フィナンシェです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      tokyoSeller("s_p036a", "アンリ・シャルパンティエ グランスタ東京店", "改札内"),
      shinagawaSeller("s_p036b", "アンリ・シャルパンティエ エキュート品川店", "改札内"),
      shinjukuSeller("s_p036c", "アンリ・シャルパンティエ 伊勢丹新宿店", "改札外"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 1000,
  },
  {
    id: "p037",
    name: "花椿ビスケット 限定缶",
    brand: "資生堂パーラー",
    price: 2160,
    priceLabel: "¥2,160（税込）",
    imageUrl: IMG.cookie,
    badges: ["local"],
    badgeLabels: ["資生堂パーラー 日持ち120日"],
    category: "クッキー",
    shelfLifeDays: 120,
    individuallyWrapped: true,
    recommendedCount: 24,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "資生堂パーラーの代表的なビスケット",
      "限定デザインの缶入り",
      "日持ち120日で余裕を持って渡せる",
      "個包装で配りやすい",
      "老舗ブランドの安心感",
    ],
    guaranteeOneLiner: "資生堂パーラーの限定缶ビスケット。日持ち120日で余裕を持って渡せる",
    makerQuote: "「資生堂パーラーの伝統と品質を、ビスケットに込めています」",
    makerStory: "資生堂パーラーは、1902年創業の老舗レストランが手がけるスイーツブランド。花椿ビスケットは代表的な商品として長年愛されている。",
    makerName: "資生堂パーラー",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。資生堂パーラーの花椿ビスケットをお持ちしました。",
      thanks: "先日はありがとうございました。資生堂パーラーの限定缶ビスケットです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      tokyoSeller("s_p037a", "資生堂パーラー グランスタ東京店", "改札内"),
      shinjukuSeller("s_p037b", "資生堂パーラー 伊勢丹新宿店", "改札外"),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び", "社内"],
    budgetCategory: 3000,
  },
  {
    id: "p038",
    name: "ドゥーブルフロマージュ",
    brand: "小樽洋菓子舗ルタオ",
    price: 2268,
    priceLabel: "¥2,268（税込）",
    imageUrl: IMG.cheese,
    badges: ["editorial"],
    badgeLabels: ["北海道の名品 グランスタ催事"],
    category: "スイーツ",
    shelfLifeDays: 2,
    individuallyWrapped: false,
    recommendedCount: 4,
    temperature: "冷凍",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "北海道小樽の人気洋菓子店",
      "ベイクドとレアの2層チーズケーキ",
      "北海道産生クリームと世界のチーズをブレンド",
      "グランスタ東京の催事で購入可能",
      "特別感のある手土産として話題になる",
    ],
    guaranteeOneLiner: "北海道小樽の名品チーズケーキ。2層仕立てのとろける口どけが絶品",
    makerQuote: "「北海道の豊かな自然が育んだ乳製品の美味しさを、チーズケーキで届けたい」",
    makerStory: "北海道小樽に本店を構える人気洋菓子店・ルタオ。ドゥーブルフロマージュは代表作として全国的に知られており、東京駅の催事でも人気。",
    makerName: "小樽洋菓子舗ルタオ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。北海道小樽のルタオのチーズケーキをお持ちしました。",
      thanks: "先日はありがとうございました。ルタオのドゥーブルフロマージュです。冷凍でお持ちしました。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [tokyoSeller("s_p038", "ルタオ POP UP GRANSTA GREEN", "改札内")],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 3000,
  },
];

// ── 選択肢データ ──────────────────────────────────────────────

export const PURPOSE_LIST = [
  { id: "挨拶", label: "挨拶", icon: "🤝", description: "初対面・訪問時" },
  { id: "御礼", label: "御礼", icon: "🙏", description: "お礼・感謝" },
  { id: "お詫び", label: "お詫び", icon: "💐", description: "謝罪・お詫び" },
  { id: "社内", label: "社内", icon: "🏢", description: "社内配布" },
  { id: "差し入れ", label: "差し入れ", icon: "☕", description: "差し入れ・おやつ" },
  { id: "自分用", label: "自分用", icon: "🎁", description: "自分へのご褒美" },
];

export const BUDGET_OPTIONS = [
  { value: 1000, label: "〜1,000円" },
  { value: 2000, label: "〜2,000円" },
  { value: 3000, label: "〜3,000円" },
  { value: 5000, label: "〜5,000円" },
];

export const SHELF_LIFE_OPTIONS = [
  { value: 0, label: "当日" },
  { value: 3, label: "3日" },
  { value: 7, label: "7日" },
  { value: 14, label: "14日以上" },
];

export const COUNT_OPTIONS = [
  { value: 5, label: "5人" },
  { value: 10, label: "10人" },
  { value: 20, label: "20人" },
  { value: 30, label: "30人" },
];

export const TEMPERATURE_OPTIONS: TemperatureType[] = ["常温", "冷蔵", "冷凍"];

export const CATEGORY_LIST = [
  "すべて", "スイーツ", "和菓子", "クッキー", "焼き菓子", "チョコレート", "スナック",
];

export interface SearchConditions {
  purpose: string;
  budget: number | null;
  shelfLife: number | null;
  individuallyWrapped: boolean | null;
  count: number | null;
  temperature: TemperatureType | null;
  facilityId: FacilityId | null;
}

// 施設フィルタ: 商品が指定施設で購入できるかチェック
function hasSellerAtFacility(product: Product, facilityId: FacilityId): boolean {
  if (facilityId === "all") return true;
  return product.sellers.some((s) => s.facilityId === facilityId);
}

export function filterProducts(conditions: SearchConditions): Product[] {
  return ALL_PRODUCTS.filter((p) => {
    if (conditions.purpose && !p.purposes.includes(conditions.purpose)) return false;
    if (conditions.budget !== null && p.price > conditions.budget) return false;
    if (conditions.shelfLife !== null && p.shelfLifeDays < conditions.shelfLife) return false;
    if (conditions.individuallyWrapped === true && !p.individuallyWrapped) return false;
    if (conditions.count !== null && p.recommendedCount < conditions.count) return false;
    if (conditions.temperature !== null && p.temperature !== conditions.temperature) return false;
    if (conditions.facilityId && conditions.facilityId !== "all") {
      if (!hasSellerAtFacility(p, conditions.facilityId)) return false;
    }
    return true;
  });
}

// フリーワード検索（全国対応）
export function searchProducts(
  query: string,
  facilityId?: FacilityId | null,
  category?: string,
  region?: RegionId | null,
  prefecture?: string | null
): Product[] {
  const q = query.trim().toLowerCase();
  return ALL_PRODUCTS.filter((p) => {
    // 施設フィルタ
    if (facilityId && facilityId !== "all") {
      if (!hasSellerAtFacility(p, facilityId)) return false;
    }
    // 地方フィルタ
    if (region && region !== "all") {
      const regionInfo = REGIONS.find((r) => r.id === region);
      if (regionInfo && regionInfo.prefectures.length > 0) {
        if (!p.prefecture || !regionInfo.prefectures.includes(p.prefecture)) return false;
      }
    }
    // 都道府県フィルタ
    if (prefecture && prefecture !== "all") {
      if (p.prefecture !== prefecture) return false;
    }
    // カテゴリフィルタ
    if (category && category !== "すべて") {
      if (p.category !== category) return false;
    }
    // フリーワード
    if (!q) return true;
    return (
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.guaranteeOneLiner.toLowerCase().includes(q) ||
      (p.prefecture && p.prefecture.toLowerCase().includes(q)) ||
      (p.region && p.region.toLowerCase().includes(q)) ||
      p.sellers.some((s) => s.shopName.toLowerCase().includes(q) || s.facilityName.toLowerCase().includes(q)) ||
      p.purposes.some((pur) => pur.includes(q)) ||
      p.allergens.some((a) => a.includes(q))
    );
  });
}

// ── 全国お土産データ（全国主要観光地15県分） ─────────────────────

// ヘルパー関数（全国施設用）
function nationalSeller(
  id: string,
  facilityId: FacilityId,
  facilityName: string,
  shopName: string,
  gate: GateStatus,
  floor: string,
  landmark: string,
  minutes: number,
  hours: string,
  coords: { lat: number; lng: number }
): Seller {
  return {
    id,
    facilityId,
    facilityName,
    shopName,
    gateStatus: gate,
    floor,
    landmark,
    walkingMinutes: minutes,
    crowdLevel: "中",
    openHours: hours,
    mapUrl: `https://maps.google.com/?q=${facilityName}`,
    coords,
  };
}

export const NATIONAL_PRODUCTS: Product[] = [
  // ─────────────────────────────────────────────────────────────
  // 北海道
  // ─────────────────────────────────────────────────────────────
  {
    id: "n001",
    name: "白い恋人",
    brand: "石屋製菓",
    price: 1296,
    priceLabel: "¥1,296（税込・18枚入）",
    imageUrl: IMG.cookie,
    badges: ["editorial"],
    badgeLabels: ["北海道土産No.1"],
    category: "クッキー",
    shelfLifeDays: 90,
    individuallyWrapped: true,
    recommendedCount: 18,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "北海道土産の代名詞として50年以上の歴史",
      "ラングドシャにホワイトチョコを挟んだ唯一無二の食感",
      "個包装で18枚入り、社内配布に最適",
      "新千歳空港・百貨店で確実に購入可能",
      "日持ち90日で余裕を持って渡せる",
    ],
    guaranteeOneLiner: "北海道土産の代名詞。50年以上愛されるラングドシャ×ホワイトチョコ",
    makerQuote: "「北海道の白い大地と澄んだ空気を、一枚のクッキーに込めました」",
    makerStory: "1976年創業の石屋製菓が生み出した北海道を代表する銘菓。ラングドシャクッキーにホワイトチョコを挟んだ独自の製法は今も変わらない。",
    makerName: "石屋製菓 製菓部門",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。北海道の定番土産をお持ちしました。",
      thanks: "先日はありがとうございました。北海道の白い恋人です。お口に合えば幸いです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn001a", "chitose", "新千歳空港", "石屋製菓 新千歳空港店", "改札外", "2F", "新千歳空港 国内線ターミナル2F", 3, "7:00〜21:00", { lat: 42.7752, lng: 141.6922 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 2000,
    prefecture: "北海道",
    region: "北海道",
  },
  {
    id: "n002",
    name: "マルセイバターサンド",
    brand: "六花亭",
    price: 1188,
    priceLabel: "¥1,188（税込・10個入）",
    imageUrl: IMG.butter,
    badges: ["editorial"],
    badgeLabels: ["帯広の老舗銘菓"],
    category: "焼き菓子",
    shelfLifeDays: 20,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "北海道帯広の老舗六花亭の代表作",
      "北海道産バターとレーズンの絶妙なハーモニー",
      "個包装で10個入り、配りやすい",
      "新千歳空港・帯広空港で購入可能",
      "日持ち20日で安心",
    ],
    guaranteeOneLiner: "帯広六花亭の銘菓。北海道産バターとレーズンが絶品のバターサンド",
    makerQuote: "「北海道の豊かな大地が育んだバターの味を、そのままサンドしました」",
    makerStory: "1933年創業の六花亭は北海道帯広を代表する老舗菓子店。マルセイバターサンドは1977年の発売以来、北海道土産の定番として愛され続けている。",
    makerName: "六花亭製菓",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。北海道帯広の六花亭をお持ちしました。",
      thanks: "先日はありがとうございました。六花亭のマルセイバターサンドです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn002a", "chitose", "新千歳空港", "六花亭 新千歳空港店", "改札外", "2F", "新千歳空港 国内線ターミナル2F", 5, "7:00〜21:00", { lat: 42.7752, lng: 141.6922 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 2000,
    prefecture: "北海道",
    region: "北海道",
  },
  {
    id: "n003",
    name: "生チョコレート（オーレ）",
    brand: "ROYCE'（ロイズ）",
    price: 756,
    priceLabel: "¥756（税込・20粒入）",
    imageUrl: IMG.chocolate,
    badges: ["editorial"],
    badgeLabels: ["SNS話題No.1"],
    category: "チョコレート",
    shelfLifeDays: 30,
    individuallyWrapped: false,
    recommendedCount: 4,
    temperature: "冷蔵",
    allergens: ["乳", "大豆"],
    guaranteeReasons: [
      "北海道生クリームを使った濃厚な口どけ",
      "SNSで話題沸騰の北海道土産",
      "新千歳空港限定フレーバーも展開",
      "冷蔵で日持ち30日",
      "価格が手頃で複数購入しやすい",
    ],
    guaranteeOneLiner: "北海道生クリーム使用の濃厚生チョコ。SNS話題No.1の定番土産",
    makerQuote: "「北海道の新鮮な生クリームだけが生み出せる、とろける口どけを追求しました」",
    makerStory: "1983年創業のロイズは北海道を代表するチョコレートブランド。生チョコレートは1993年の発売以来、北海道土産の定番として世界中にファンを持つ。",
    makerName: "ROYCE' チョコレートワールド",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。北海道ロイズの生チョコをお持ちしました。",
      thanks: "先日はありがとうございました。ロイズの生チョコレートです。冷蔵でお持ちしました。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn003a", "chitose", "新千歳空港", "ROYCE' チョコレートワールド", "改札外", "2F", "新千歳空港 国内線ターミナル2F", 3, "7:00〜21:00", { lat: 42.7752, lng: 141.6922 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ", "自分用"],
    budgetCategory: 1000,
    prefecture: "北海道",
    region: "北海道",
  },

  // ─────────────────────────────────────────────────────────────
  // 宮城県（仙台）
  // ─────────────────────────────────────────────────────────────
  {
    id: "n004",
    name: "萩の月",
    brand: "菓匠三全",
    price: 1188,
    priceLabel: "¥1,188（税込・6個入）",
    imageUrl: IMG.cake,
    badges: ["editorial"],
    badgeLabels: ["仙台銘菓の代名詞"],
    category: "スイーツ",
    shelfLifeDays: 10,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "仙台を代表する銘菓として40年以上の歴史",
      "ふんわりカステラ生地にカスタードクリームが絶品",
      "個包装で6個入り、配りやすい",
      "仙台駅・仙台空港で確実に購入可能",
      "日持ち10日で安心",
    ],
    guaranteeOneLiner: "仙台の代名詞。ふんわりカステラ×カスタードクリームの絶品銘菓",
    makerQuote: "「宮城の豊かな自然をイメージした、丸くやわらかな月のお菓子です」",
    makerStory: "1979年創業の菓匠三全が生み出した仙台を代表する銘菓。宮城野の空に浮かぶ満月をイメージした丸いフォルムが特徴。",
    makerName: "菓匠三全",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。仙台の萩の月をお持ちしました。",
      thanks: "先日はありがとうございました。仙台銘菓の萩の月です。お口に合えば幸いです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn004a", "sendai", "仙台駅", "菓匠三全 仙台駅店", "改札内", "2F", "仙台駅 2F エスパル仙台", 3, "8:00〜21:00", { lat: 38.2682, lng: 140.8694 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内"],
    budgetCategory: 2000,
    prefecture: "宮城県",
    region: "東北",
  },

  // ─────────────────────────────────────────────────────────────
  // 長野県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n005",
    name: "雷鳥の里",
    brand: "田中屋",
    price: 972,
    priceLabel: "¥972（税込・16個入）",
    imageUrl: IMG.cookie,
    badges: ["local"],
    badgeLabels: ["長野の定番銘菓"],
    category: "焼き菓子",
    shelfLifeDays: 60,
    individuallyWrapped: true,
    recommendedCount: 16,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "長野を代表する定番銘菓として長年愛される",
      "クリームを挟んだウエハースの軽い食感",
      "個包装16個入りで社内配布に最適",
      "長野駅・松本駅で購入可能",
      "日持ち60日で余裕あり",
    ],
    guaranteeOneLiner: "長野の定番銘菓。クリームウエハースの軽い食感が万人受け",
    makerQuote: "「北アルプスの雷鳥のように、軽やかで爽やかなお菓子を目指しました」",
    makerStory: "長野県を代表する菓子メーカー・田中屋が手がける定番銘菓。北アルプスの雷鳥をモチーフにしたパッケージが親しまれている。",
    makerName: "田中屋",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。長野の雷鳥の里をお持ちしました。",
      thanks: "先日はありがとうございました。長野銘菓の雷鳥の里です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn005a", "nagano", "長野駅", "田中屋 長野駅店", "改札内", "1F", "長野駅 改札内ショップ", 2, "7:00〜21:00", { lat: 36.6485, lng: 138.1950 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "社内", "差し入れ"],
    budgetCategory: 1000,
    prefecture: "長野県",
    region: "中部",
  },

  // ─────────────────────────────────────────────────────────────
  // 石川県（金沢）
  // ─────────────────────────────────────────────────────────────
  {
    id: "n006",
    name: "きんつば（丸型）",
    brand: "中田屋",
    price: 1512,
    priceLabel: "¥1,512（税込・6個入）",
    imageUrl: IMG.wagashi,
    badges: ["editorial"],
    badgeLabels: ["金沢銘菓 創業80年"],
    category: "和菓子",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦"],
    guaranteeReasons: [
      "金沢を代表する老舗和菓子店・中田屋の看板商品",
      "北陸産小豆を使った上品な甘さ",
      "丸型きんつばは中田屋独自のスタイル",
      "金沢駅 百番街で購入可能",
      "日持ち14日で安心",
    ],
    guaranteeOneLiner: "金沢老舗・中田屋の丸型きんつば。北陸産小豆の上品な甘さが絶品",
    makerQuote: "「金沢の和菓子文化を守りながら、丸型という独自のスタイルで愛され続けています」",
    makerStory: "1934年創業の中田屋は金沢を代表する和菓子店。丸型きんつばは全国的に珍しいスタイルで、金沢の和菓子文化を象徴する一品。",
    makerName: "中田屋 職人",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。金沢中田屋のきんつばをお持ちしました。",
      thanks: "先日はありがとうございました。金沢の老舗・中田屋のきんつばです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn006a", "kanazawa", "金沢駅", "中田屋 金沢駅 百番街店", "改札外", "1F", "金沢駅 百番街あんと", 3, "8:30〜20:00", { lat: 36.5781, lng: 136.6480 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 2000,
    prefecture: "石川県",
    region: "中部",
  },
  {
    id: "n007",
    name: "加賀棒茶フィナンシェ",
    brand: "ル ミュゼ ドゥ アッシュ",
    price: 2160,
    priceLabel: "¥2,160（税込・8個入）",
    imageUrl: IMG.financier,
    badges: ["editorial"],
    badgeLabels: ["金沢スイーツの新定番"],
    category: "焼き菓子",
    shelfLifeDays: 30,
    individuallyWrapped: true,
    recommendedCount: 8,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "金沢の人気パティシエ・辻口博啓氏プロデュース",
      "加賀棒茶の香りとフィナンシェの絶妙な組み合わせ",
      "金沢らしい上品な手土産として話題",
      "金沢駅 百番街で購入可能",
      "日持ち30日で余裕あり",
    ],
    guaranteeOneLiner: "辻口博啓氏プロデュース。加賀棒茶香るフィナンシェは金沢スイーツの新定番",
    makerQuote: "「金沢の伝統・加賀棒茶の香りをフランス菓子に融合させました」",
    makerStory: "世界的パティシエ・辻口博啓氏が手がける金沢発のスイーツブランド。加賀棒茶を使った独自のフィナンシェは金沢土産として急速に人気を集めている。",
    makerName: "辻口博啓 パティシエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。金沢の加賀棒茶フィナンシェをお持ちしました。",
      thanks: "先日はありがとうございました。金沢の人気スイーツです。お口に合えば幸いです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn007a", "kanazawa", "金沢駅", "ル ミュゼ ドゥ アッシュ 金沢駅店", "改札外", "1F", "金沢駅 百番街あんと", 3, "8:30〜20:00", { lat: 36.5781, lng: 136.6480 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 3000,
    prefecture: "石川県",
    region: "中部",
  },

  // ─────────────────────────────────────────────────────────────
  // 静岡県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n008",
    name: "うなぎパイ",
    brand: "春華堂",
    price: 1080,
    priceLabel: "¥1,080（税込・12本入）",
    imageUrl: IMG.rusk,
    badges: ["editorial"],
    badgeLabels: ["夜のお菓子 浜松銘菓"],
    category: "焼き菓子",
    shelfLifeDays: 30,
    individuallyWrapped: true,
    recommendedCount: 12,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "浜松を代表する銘菓として60年以上の歴史",
      "うなぎエキスを使った独特の風味",
      "個包装12本入りで配りやすい",
      "静岡駅・浜松駅で購入可能",
      "日持ち30日で安心",
    ],
    guaranteeOneLiner: "浜松60年の銘菓。うなぎエキス入りパイは「夜のお菓子」として有名",
    makerQuote: "「浜松の名産うなぎをお菓子で表現した、唯一無二の味わいです」",
    makerStory: "1952年創業の春華堂が生み出した浜松銘菓。「夜のお菓子」というキャッチコピーで全国的に知られ、静岡を代表するお土産として定着している。",
    makerName: "春華堂",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。浜松の春華堂のうなぎパイをお持ちしました。",
      thanks: "先日はありがとうございました。浜松銘菓のうなぎパイです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn008a", "shizuoka", "浜松駅", "春華堂 浜松駅店", "改札外", "1F", "浜松駅 メイワン", 3, "8:00〜21:00", { lat: 34.7031, lng: 137.7348 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 2000,
    prefecture: "静岡県",
    region: "中部",
  },

  // ─────────────────────────────────────────────────────────────
  // 京都府
  // ─────────────────────────────────────────────────────────────
  {
    id: "n009",
    name: "お濃茶ラングドシャ 茶の菓",
    brand: "マールブランシュ",
    price: 1296,
    priceLabel: "¥1,296（税込・10枚入）",
    imageUrl: IMG.cookie,
    badges: ["editorial"],
    badgeLabels: ["京都土産ランキング常連"],
    category: "クッキー",
    shelfLifeDays: 60,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "京都土産ランキングで常に上位の人気商品",
      "京都産お濃茶を使ったラングドシャ",
      "ホワイトチョコとの絶妙なバランス",
      "京都駅 ジェイアール京都伊勢丹で購入可能",
      "日持ち60日で余裕あり",
    ],
    guaranteeOneLiner: "京都産お濃茶×ホワイトチョコのラングドシャ。京都土産ランキング常連",
    makerQuote: "「京都の宇治抹茶の深い味わいを、ラングドシャに閉じ込めました」",
    makerStory: "1982年創業のマールブランシュは京都北山に本店を構える洋菓子店。茶の菓は2003年の発売以来、京都を代表するお土産として全国的な人気を誇る。",
    makerName: "マールブランシュ 京都北山",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。京都マールブランシュの茶の菓をお持ちしました。",
      thanks: "先日はありがとうございました。京都の人気土産・茶の菓です。お口に合えば幸いです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn009a", "kyoto", "京都駅", "マールブランシュ 京都駅店", "改札外", "2F", "ジェイアール京都伊勢丹 B1F", 5, "10:00〜20:00", { lat: 34.9858, lng: 135.7588 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び", "社内"],
    budgetCategory: 2000,
    prefecture: "京都府",
    region: "近畿",
  },
  {
    id: "n010",
    name: "生八つ橋（ニッキ）",
    brand: "おたべ",
    price: 756,
    priceLabel: "¥756（税込・10個入）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["京都1300年の伝統菓子"],
    category: "和菓子",
    shelfLifeDays: 7,
    individuallyWrapped: false,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦"],
    guaranteeReasons: [
      "京都1300年の歴史を持つ伝統菓子",
      "ニッキの香りが京都らしさを演出",
      "京都駅・清水寺周辺で購入可能",
      "価格が手頃で複数購入しやすい",
      "京都土産の定番として誰もが知っている",
    ],
    guaranteeOneLiner: "京都1300年の伝統。ニッキ香る生八つ橋は京都土産の絶対定番",
    makerQuote: "「京都の伝統を守りながら、現代の人にも愛される生八つ橋を作り続けています」",
    makerStory: "京都を代表する和菓子・八つ橋。おたべは1957年創業で、生八つ橋の普及に貢献した老舗。ニッキ（シナモン）の香りが京都らしさを象徴する。",
    makerName: "おたべ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。京都の生八つ橋をお持ちしました。",
      thanks: "先日はありがとうございました。京都の定番・生八つ橋です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn010a", "kyoto", "京都駅", "おたべ 京都駅店", "改札外", "1F", "京都駅 八条口", 5, "9:00〜21:00", { lat: 34.9858, lng: 135.7588 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ", "社内"],
    budgetCategory: 1000,
    prefecture: "京都府",
    region: "近畿",
  },
  {
    id: "n011",
    name: "阿闍梨餅",
    brand: "満月",
    price: 1404,
    priceLabel: "¥1,404（税込・10個入）",
    imageUrl: IMG.wagashi,
    badges: ["editorial"],
    badgeLabels: ["京都人が選ぶ手土産No.1"],
    category: "和菓子",
    shelfLifeDays: 5,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦", "卵"],
    guaranteeReasons: [
      "京都人が選ぶ手土産ランキングで常に上位",
      "丹波大納言小豆を使った上品な餡",
      "もちもちした独特の食感",
      "京都駅・百貨店で購入可能",
      "個包装で10個入り",
    ],
    guaranteeOneLiner: "京都人が選ぶ手土産No.1。丹波大納言小豆のもちもち餡菓子",
    makerQuote: "「比叡山で修行する阿闍梨のように、一つ一つ丁寧に作り上げています」",
    makerStory: "1856年創業の満月が手がける京都銘菓。比叡山で修行する阿闍梨が持ち歩く笠をモチーフにした丸い形が特徴。京都人自身が手土産に選ぶ定番品。",
    makerName: "満月 職人",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。京都満月の阿闍梨餅をお持ちしました。",
      thanks: "先日はありがとうございました。京都で人気の阿闍梨餅です。お口に合えば幸いです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn011a", "kyoto", "京都駅", "満月 京都駅店", "改札外", "2F", "ジェイアール京都伊勢丹 B1F", 5, "10:00〜20:00", { lat: 34.9858, lng: 135.7588 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "soldout_risk",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 2000,
    prefecture: "京都府",
    region: "近畿",
  },

  // ─────────────────────────────────────────────────────────────
  // 大阪府
  // ─────────────────────────────────────────────────────────────
  {
    id: "n012",
    name: "堂島ロール",
    brand: "モンシェール",
    price: 1728,
    priceLabel: "¥1,728（税込）",
    imageUrl: IMG.cake,
    badges: ["editorial"],
    badgeLabels: ["大阪スイーツの新定番"],
    category: "スイーツ",
    shelfLifeDays: 3,
    individuallyWrapped: false,
    recommendedCount: 6,
    temperature: "冷蔵",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "大阪・堂島発のロールケーキブームを牽引",
      "生クリームたっぷりの贅沢な一本",
      "新大阪駅・大阪駅で購入可能",
      "SNSで話題の大阪スイーツ",
      "冷蔵で日持ち3日",
    ],
    guaranteeOneLiner: "大阪堂島発のロールケーキブームの火付け役。生クリームたっぷりの贅沢品",
    makerQuote: "「大阪・堂島の地から、日本中においしいロールケーキを届けたい」",
    makerStory: "2004年に大阪・堂島に誕生したモンシェール。堂島ロールは発売当初から行列が絶えない人気商品で、大阪スイーツブームを牽引した一品。",
    makerName: "モンシェール パティシエ",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。大阪堂島ロールをお持ちしました。",
      thanks: "先日はありがとうございました。大阪の人気スイーツ・堂島ロールです。冷蔵でお持ちしました。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn012a", "osaka", "新大阪駅", "モンシェール 新大阪駅店", "改札外", "1F", "新大阪駅 駅ビル1F", 5, "8:00〜21:00", { lat: 34.7333, lng: 135.5000 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 2000,
    prefecture: "大阪府",
    region: "近畿",
  },
  {
    id: "n013",
    name: "りくろーおじさんのチーズケーキ",
    brand: "りくろーおじさんの店",
    price: 965,
    priceLabel: "¥965（税込・1ホール）",
    imageUrl: IMG.cheese,
    badges: ["editorial"],
    badgeLabels: ["大阪No.1チーズケーキ"],
    category: "スイーツ",
    shelfLifeDays: 3,
    individuallyWrapped: false,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "大阪で常に行列ができる人気チーズケーキ",
      "デンマーク産クリームチーズ使用のふわふわ食感",
      "焼き立てを提供する新大阪駅店が人気",
      "価格が手頃で喜ばれやすい",
      "大阪土産として知名度抜群",
    ],
    guaranteeOneLiner: "大阪で常に行列。デンマーク産クリームチーズのふわふわチーズケーキ",
    makerQuote: "「焼き立てのふわふわ食感を、できるだけ多くの人に届けたい」",
    makerStory: "1956年創業のりくろーおじさんの店。新大阪駅店では常に行列ができ、焼き立てのチーズケーキが大阪土産として定着している。",
    makerName: "りくろーおじさんの店",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。大阪の人気チーズケーキをお持ちしました。",
      thanks: "先日はありがとうございました。りくろーおじさんのチーズケーキです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn013a", "osaka", "新大阪駅", "りくろーおじさんの店 新大阪駅店", "改札外", "1F", "新大阪駅 駅ビル1F", 3, "8:00〜21:00", { lat: 34.7333, lng: 135.5000 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "差し入れ"],
    budgetCategory: 1000,
    prefecture: "大阪府",
    region: "近畿",
  },

  // ─────────────────────────────────────────────────────────────
  // 奈良県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n014",
    name: "奈良漬",
    brand: "今西本店",
    price: 1620,
    priceLabel: "¥1,620（税込・200g）",
    imageUrl: IMG.snack,
    badges: ["local"],
    badgeLabels: ["奈良1300年の伝統"],
    category: "その他",
    shelfLifeDays: 180,
    individuallyWrapped: false,
    recommendedCount: 4,
    temperature: "常温",
    allergens: [],
    guaranteeReasons: [
      "奈良1300年の歴史を持つ伝統的な漬物",
      "奈良の清酒の酒粕で漬け込んだ深い味わい",
      "日持ち180日で余裕を持って渡せる",
      "近鉄奈良駅・JR奈良駅周辺で購入可能",
      "奈良土産の定番として誰もが知っている",
    ],
    guaranteeOneLiner: "奈良1300年の伝統漬物。清酒の酒粕で漬け込んだ深い味わい",
    makerQuote: "「奈良の清酒文化と漬物文化が融合した、唯一無二の味わいです」",
    makerStory: "今西本店は奈良を代表する奈良漬の老舗。奈良の清酒の酒粕を使った伝統的な製法を守り続けている。",
    makerName: "今西本店",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。奈良の伝統・奈良漬をお持ちしました。",
      thanks: "先日はありがとうございました。奈良の老舗・今西本店の奈良漬です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn014a", "nara", "近鉄奈良駅", "今西本店 近鉄奈良駅店", "改札外", "1F", "近鉄奈良駅 改札外", 3, "9:00〜19:00", { lat: 34.6851, lng: 135.8048 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼"],
    budgetCategory: 2000,
    prefecture: "奈良県",
    region: "近畿",
  },

  // ─────────────────────────────────────────────────────────────
  // 広島県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n015",
    name: "生もみじ",
    brand: "にしき堂",
    price: 1080,
    priceLabel: "¥1,080（税込・8個入）",
    imageUrl: IMG.wagashi,
    badges: ["editorial"],
    badgeLabels: ["広島土産ランキング1位"],
    category: "和菓子",
    shelfLifeDays: 7,
    individuallyWrapped: true,
    recommendedCount: 8,
    temperature: "常温",
    allergens: ["小麦", "卵"],
    guaranteeReasons: [
      "広島土産ランキングで連続1位を獲得",
      "もちもちした生地に包まれた上品な餡",
      "こしあん・粒あん・クリームチーズなど多彩なフレーバー",
      "広島駅・宮島で購入可能",
      "個包装8個入りで配りやすい",
    ],
    guaranteeOneLiner: "広島土産ランキング1位。もちもち生地の生もみじは定番中の定番",
    makerQuote: "「広島の紅葉をイメージした、やわらかくて上品なもみじ饅頭を作りました」",
    makerStory: "1951年創業のにしき堂が手がける広島銘菓。従来のもみじ饅頭とは異なるもちもちした生地が特徴の「生もみじ」は、広島土産の新定番として人気を集めている。",
    makerName: "にしき堂",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。広島の生もみじをお持ちしました。",
      thanks: "先日はありがとうございました。広島土産ランキング1位の生もみじです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn015a", "hiroshima", "広島駅", "にしき堂 広島駅店", "改札外", "1F", "広島駅 ekie", 3, "8:00〜21:00", { lat: 34.3963, lng: 132.4596 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 2000,
    prefecture: "広島県",
    region: "中国",
  },

  // ─────────────────────────────────────────────────────────────
  // 愛知県（名古屋）
  // ─────────────────────────────────────────────────────────────
  {
    id: "n016",
    name: "ぴよりん",
    brand: "名古屋観光ホテル",
    price: 540,
    priceLabel: "¥540（税込・1個）",
    imageUrl: IMG.cake,
    badges: ["editorial"],
    badgeLabels: ["SNS話題 名古屋土産No.1"],
    category: "スイーツ",
    shelfLifeDays: 2,
    individuallyWrapped: false,
    recommendedCount: 1,
    temperature: "冷蔵",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "2024年おみやげランキング1位を獲得",
      "ひよこ型のプリンスイーツがSNSで大バズり",
      "名古屋駅・中部国際空港で購入可能",
      "見た目のインパクトで話題になること確実",
      "名古屋土産の新定番として定着",
    ],
    guaranteeOneLiner: "2024年おみやげランキング1位。ひよこ型プリンがSNSで大バズり",
    makerQuote: "「かわいいひよこの形に、名古屋コーチンの卵を使ったプリンを詰め込みました」",
    makerStory: "名古屋観光ホテルが手がけるひよこ型のプリンスイーツ。SNSでの話題性が高く、2024年のおみやげランキングで1位を獲得した名古屋の新定番土産。",
    makerName: "名古屋観光ホテル",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。名古屋の話題スイーツ・ぴよりんをお持ちしました。",
      thanks: "先日はありがとうございました。SNSで大人気のぴよりんです。冷蔵でお持ちしました。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn016a", "nagoya", "名古屋駅", "ぴよりん SHOP 名古屋駅店", "改札内", "1F", "名古屋駅 JR名古屋タカシマヤ", 3, "10:00〜21:00", { lat: 35.1709, lng: 136.8815 }),
    ],
    canReserve: true,
    canPrePay: false,
    canDeliver: false,
    stockStatus: "soldout_risk",
    purposes: ["差し入れ", "自分用", "御礼"],
    budgetCategory: 1000,
    prefecture: "愛知県",
    region: "中部",
  },
  {
    id: "n017",
    name: "なごやん",
    brand: "不二家",
    price: 864,
    priceLabel: "¥864（税込・12個入）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["名古屋の定番銘菓"],
    category: "和菓子",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 12,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "名古屋を代表する定番銘菓として長年愛される",
      "ふんわりした生地に白あんを包んだ上品な味",
      "個包装12個入りで社内配布に最適",
      "名古屋駅・中部国際空港で購入可能",
      "日持ち14日で安心",
    ],
    guaranteeOneLiner: "名古屋の定番銘菓。ふんわり生地×白あんの上品な味わい",
    makerQuote: "「名古屋の人々に長年愛されてきた、シンプルで上品な味を守り続けています」",
    makerStory: "不二家が手がける名古屋限定の銘菓。名古屋を代表するお土産として、地元民から観光客まで幅広く支持されている。",
    makerName: "不二家",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。名古屋の定番・なごやんをお持ちしました。",
      thanks: "先日はありがとうございました。名古屋銘菓のなごやんです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn017a", "nagoya", "名古屋駅", "不二家 名古屋駅店", "改札外", "1F", "名古屋駅 JR名古屋タカシマヤ B1F", 5, "10:00〜20:00", { lat: 35.1709, lng: 136.8815 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "社内", "差し入れ"],
    budgetCategory: 1000,
    prefecture: "愛知県",
    region: "中部",
  },

  // ─────────────────────────────────────────────────────────────
  // 福岡県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n018",
    name: "博多通りもん",
    brand: "明月堂",
    price: 1080,
    priceLabel: "¥1,080（税込・8個入）",
    imageUrl: IMG.wagashi,
    badges: ["editorial"],
    badgeLabels: ["全国菓子大博覧会 最高賞"],
    category: "和菓子",
    shelfLifeDays: 20,
    individuallyWrapped: true,
    recommendedCount: 8,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "全国菓子大博覧会で最高賞を受賞",
      "博多土産ランキングで常に上位",
      "ミルク風味の白あんが絶品",
      "博多駅・福岡空港で確実に購入可能",
      "個包装8個入りで配りやすい",
    ],
    guaranteeOneLiner: "全国菓子大博覧会最高賞。博多土産の代名詞・ミルク白あんが絶品",
    makerQuote: "「博多の人々に愛され続けてきた、ミルク風味の白あんの美味しさを届けます」",
    makerStory: "1956年創業の明月堂が手がける博多銘菓。全国菓子大博覧会で最高賞を受賞し、博多土産の定番として全国的な知名度を誇る。",
    makerName: "明月堂",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。博多の博多通りもんをお持ちしました。",
      thanks: "先日はありがとうございました。博多土産の定番・博多通りもんです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn018a", "fukuoka", "博多駅", "明月堂 博多駅店", "改札内", "1F", "博多駅 マイング", 3, "7:00〜22:00", { lat: 33.5903, lng: 130.4207 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 2000,
    prefecture: "福岡県",
    region: "九州・沖縄",
  },
  {
    id: "n019",
    name: "めんべい",
    brand: "山口油屋福太郎",
    price: 648,
    priceLabel: "¥648（税込・16枚入）",
    imageUrl: IMG.snack,
    badges: ["local"],
    badgeLabels: ["博多の辛口スナック"],
    category: "スナック",
    shelfLifeDays: 60,
    individuallyWrapped: true,
    recommendedCount: 16,
    temperature: "常温",
    allergens: ["小麦", "えび", "いか"],
    guaranteeReasons: [
      "博多の辛口スナックとして全国的な人気",
      "明太子とえびの風味が絶妙",
      "個包装16枚入りで社内配布に最適",
      "博多駅・福岡空港で確実に購入可能",
      "日持ち60日で余裕あり",
    ],
    guaranteeOneLiner: "博多の辛口スナック。明太子×えびの風味が癖になる全国人気品",
    makerQuote: "「博多の明太子文化をスナックで表現した、やみつきになる一品です」",
    makerStory: "山口油屋福太郎が手がける博多の辛口スナック。明太子とえびの風味が絶妙で、博多土産として全国的な人気を誇る。",
    makerName: "山口油屋福太郎",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。博多のめんべいをお持ちしました。",
      thanks: "先日はありがとうございました。博多の人気スナック・めんべいです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn019a", "fukuoka", "博多駅", "山口油屋福太郎 博多駅店", "改札内", "1F", "博多駅 マイング", 3, "7:00〜22:00", { lat: 33.5903, lng: 130.4207 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "社内", "差し入れ"],
    budgetCategory: 1000,
    prefecture: "福岡県",
    region: "九州・沖縄",
  },

  // ─────────────────────────────────────────────────────────────
  // 長崎県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n020",
    name: "長崎カステラ（0番）",
    brand: "福砂屋",
    price: 2160,
    priceLabel: "¥2,160（税込・小1本）",
    imageUrl: IMG.cake,
    badges: ["editorial"],
    badgeLabels: ["長崎400年の伝統銘菓"],
    category: "焼き菓子",
    shelfLifeDays: 21,
    individuallyWrapped: false,
    recommendedCount: 8,
    temperature: "常温",
    allergens: ["小麦", "卵"],
    guaranteeReasons: [
      "1624年創業・長崎カステラの老舗中の老舗",
      "ザラメ糖の食感が特徴の伝統製法",
      "長崎土産の代名詞として400年の歴史",
      "長崎駅・長崎空港で購入可能",
      "日持ち21日で安心",
    ],
    guaranteeOneLiner: "1624年創業・長崎カステラの老舗。ザラメ糖の食感が伝統の証",
    makerQuote: "「400年変わらぬ製法で、長崎の伝統の味を守り続けています」",
    makerStory: "1624年創業の福砂屋は長崎カステラの老舗中の老舗。ザラメ糖を底に敷いた独特の製法は今も変わらず、長崎を代表する銘菓として全国に知られる。",
    makerName: "福砂屋",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。長崎の老舗・福砂屋のカステラをお持ちしました。",
      thanks: "先日はありがとうございました。長崎銘菓の福砂屋カステラです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn020a", "nagasaki", "長崎駅", "福砂屋 長崎駅店", "改札外", "1F", "長崎駅 アミュプラザ長崎", 3, "9:00〜21:00", { lat: 32.7503, lng: 129.8779 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "お詫び"],
    budgetCategory: 3000,
    prefecture: "長崎県",
    region: "九州・沖縄",
  },

  // ─────────────────────────────────────────────────────────────
  // 熊本県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n021",
    name: "陣太鼓",
    brand: "お菓子の香梅",
    price: 1296,
    priceLabel: "¥1,296（税込・6個入）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["熊本銘菓 50年の歴史"],
    category: "和菓子",
    shelfLifeDays: 14,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦"],
    guaranteeReasons: [
      "熊本を代表する銘菓として50年以上の歴史",
      "栗入り羊羹の上品な甘さ",
      "個包装6個入りで配りやすい",
      "熊本駅・熊本空港で購入可能",
      "日持ち14日で安心",
    ],
    guaranteeOneLiner: "熊本50年の銘菓。栗入り羊羹の上品な甘さが万人受け",
    makerQuote: "「熊本の豊かな自然が育んだ栗を使った、上品な羊羹です」",
    makerStory: "お菓子の香梅が手がける熊本銘菓。加藤清正の陣太鼓をモチーフにした名前と、栗入り羊羹の上品な味わいが特徴。",
    makerName: "お菓子の香梅",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。熊本の陣太鼓をお持ちしました。",
      thanks: "先日はありがとうございました。熊本銘菓の陣太鼓です。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn021a", "kumamoto", "熊本駅", "お菓子の香梅 熊本駅店", "改札外", "1F", "熊本駅 アミュプラザくまもと", 3, "9:00〜21:00", { lat: 32.7898, lng: 130.7417 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内"],
    budgetCategory: 2000,
    prefecture: "熊本県",
    region: "九州・沖縄",
  },

  // ─────────────────────────────────────────────────────────────
  // 鹿児島県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n022",
    name: "かるかん",
    brand: "明石屋",
    price: 1296,
    priceLabel: "¥1,296（税込・6個入）",
    imageUrl: IMG.wagashi,
    badges: ["local"],
    badgeLabels: ["薩摩藩の伝統銘菓"],
    category: "和菓子",
    shelfLifeDays: 7,
    individuallyWrapped: true,
    recommendedCount: 6,
    temperature: "常温",
    allergens: ["小麦", "卵"],
    guaranteeReasons: [
      "薩摩藩時代から続く鹿児島の伝統銘菓",
      "山芋を使ったふんわりした独特の食感",
      "個包装6個入りで配りやすい",
      "鹿児島中央駅で購入可能",
      "日持ち7日",
    ],
    guaranteeOneLiner: "薩摩藩の伝統銘菓。山芋使用のふんわり食感が鹿児島の誇り",
    makerQuote: "「薩摩の山芋と米粉が生み出す、ふんわりとした食感を大切にしています」",
    makerStory: "1834年創業の明石屋は鹿児島を代表する老舗和菓子店。かるかんは薩摩藩時代から続く伝統菓子で、山芋を使ったふんわりした食感が特徴。",
    makerName: "明石屋",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。鹿児島の伝統菓子・かるかんをお持ちしました。",
      thanks: "先日はありがとうございました。鹿児島銘菓のかるかんです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn022a", "kagoshima", "鹿児島中央駅", "明石屋 鹿児島中央駅店", "改札外", "1F", "鹿児島中央駅 アミュプラザ鹿児島", 3, "9:00〜21:00", { lat: 31.5785, lng: 130.5432 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内"],
    budgetCategory: 2000,
    prefecture: "鹿児島県",
    region: "九州・沖縄",
  },

  // ─────────────────────────────────────────────────────────────
  // 沖縄県
  // ─────────────────────────────────────────────────────────────
  {
    id: "n023",
    name: "紅いもタルト",
    brand: "御菓子御殿",
    price: 1188,
    priceLabel: "¥1,188（税込・10個入）",
    imageUrl: IMG.tart,
    badges: ["editorial"],
    badgeLabels: ["沖縄土産No.1"],
    category: "スイーツ",
    shelfLifeDays: 30,
    individuallyWrapped: true,
    recommendedCount: 10,
    temperature: "常温",
    allergens: ["小麦", "卵", "乳"],
    guaranteeReasons: [
      "沖縄土産ランキングで常に上位の定番品",
      "沖縄県産紅芋100%使用の鮮やかな紫色",
      "個包装10個入りで社内配布に最適",
      "那覇空港・国際通りで確実に購入可能",
      "日持ち30日で余裕あり",
    ],
    guaranteeOneLiner: "沖縄土産No.1。県産紅芋100%使用の鮮やかな紫色タルト",
    makerQuote: "「沖縄の豊かな土地が育んだ紅芋の美味しさを、タルトに込めました」",
    makerStory: "御菓子御殿が手がける沖縄銘菓。沖縄県産紅芋100%使用の鮮やかな紫色が特徴で、沖縄土産の定番として全国的な知名度を誇る。",
    makerName: "御菓子御殿",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。沖縄の紅いもタルトをお持ちしました。",
      thanks: "先日はありがとうございました。沖縄土産の定番・紅いもタルトです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn023a", "naha", "那覇空港", "御菓子御殿 那覇空港店", "改札外", "2F", "那覇空港 国内線2F", 3, "7:00〜21:00", { lat: 26.2124, lng: 127.6492 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "御礼", "社内", "差し入れ"],
    budgetCategory: 2000,
    prefecture: "沖縄県",
    region: "九州・沖縄",
  },
  {
    id: "n024",
    name: "雪塩ちんすこう",
    brand: "南風堂",
    price: 864,
    priceLabel: "¥864（税込・24個入）",
    imageUrl: IMG.cookie,
    badges: ["local"],
    badgeLabels: ["沖縄の塩菓子 SNS話題"],
    category: "クッキー",
    shelfLifeDays: 60,
    individuallyWrapped: true,
    recommendedCount: 24,
    temperature: "常温",
    allergens: ["小麦", "乳"],
    guaranteeReasons: [
      "沖縄の伝統菓子ちんすこうに雪塩をプラス",
      "甘じょっぱい味わいがSNSで話題",
      "個包装24個入りで大人数配布に最適",
      "那覇空港・国際通りで確実に購入可能",
      "日持ち60日で余裕あり",
    ],
    guaranteeOneLiner: "沖縄の伝統×雪塩の甘じょっぱさ。SNS話題の大人数向け定番品",
    makerQuote: "「宮古島の雪塩と沖縄の伝統菓子ちんすこうを組み合わせた、新しい沖縄の味です」",
    makerStory: "南風堂が手がける沖縄銘菓。宮古島産の雪塩を使ったちんすこうは、甘じょっぱい味わいがSNSで話題となり、沖縄土産の新定番として人気を集めている。",
    makerName: "南風堂",
    giftTemplates: {
      greeting: "本日はお時間をいただきありがとうございます。沖縄の雪塩ちんすこうをお持ちしました。",
      thanks: "先日はありがとうございました。沖縄の人気土産・雪塩ちんすこうです。",
      apology: "このたびはご迷惑をおかけし申し訳ございません。心ばかりの品をお受け取りください。",
    },
    sellers: [
      nationalSeller("sn024a", "naha", "那覇空港", "南風堂 那覇空港店", "改札外", "2F", "那覇空港 国内線2F", 3, "7:00〜21:00", { lat: 26.2124, lng: 127.6492 }),
    ],
    canReserve: false,
    canPrePay: false,
    canDeliver: true,
    stockStatus: "available",
    purposes: ["挨拶", "社内", "差し入れ"],
    budgetCategory: 1000,
    prefecture: "沖縄県",
    region: "九州・沖縄",
  },
];

// 全商品データ（都内 + 全国）
export const ALL_PRODUCTS: Product[] = [...PRODUCTS, ...NATIONAL_PRODUCTS];
